Uxd
kubevirt/kubevirt.github.io pull request #612
Opened 2020-08-11 16:21 UTC by mazzystr

**What this PR does / why we need it**:
mazzystr fork branch uxd will contain all issue fixes from UXD team so we can release as a single package

2020-08-11 16:49 UTC, mazzystr commented
/retest

2020-08-11 19:19 UTC, mazzystr commented
/retest

2020-08-12 16:58 UTC, mazzystr commented
/retest

2020-08-24 22:04 UTC, mazzystr commented
@codificat @fabiand  Please review the following...
* Front page ... boundary borders loosened up
* Front page ...  Panel with recent blog posts added
* Front/Community page ... Try It! buttons modernized
* Blogs/Labs page ... left panel font size and position should match

2020-08-31 10:58 UTC, dankenigsberg commented
> @codificat @fabiand Please review the following...
> 
>     * Front page ... boundary borders loosened up
> 
>     * Front page ...  Panel with recent blog posts added
> 
>     * Front/Community page ... Try It! buttons modernized
> 
>     * Blogs/Labs page ... left panel font size and position should match

@mazzystr can you put this can of explanation at the to description of the PR. How would you recommend to a layperson like myself to review the change?

2020-09-28 17:43 UTC, codificat requested changes
Only some minor things to update.

There are also a couple of design questions/comments, like the white gap above the main title in the labs and the left pane's lack of margin/padding on that page, but I think these are better addressed as minor follow-ups, so we don't delay this one any longer.

2020-09-30 15:57 UTC, mazzystr commented
/retest

2020-09-30 16:12 UTC, mazzystr commented on index.html
> +      <time datetime="1999-12-23" class="">{{ post.date | date: "%a, %-d/%m/%y" }}</time>
I don't understand the commit or comment.  Let's issue this and move fwd.

2020-09-30 19:01 UTC, codificat commented
Blocker issues were addressed, so in the interest of moving this bulk update forward:

/lgtm
/approve

There are some issues to be addressed here, but we'll open separate/specific issues/PRs to review them, including:
- date formatting in the new /Recent posts/ sidebar in the home page
- margins/padding of the left side bar and the main content area in labs and blogs
- block spacing has been fixed, but it might be that some existing content had workarounds for that (e.g. `<br>` lines) that should be cleaned up

2020-09-30 19:03 UTC, merged