Update README to add cmd for link checker
kubevirt/kubevirt.github.io pull request #619
Opened 2020-08-28 21:50 UTC by mazzystr

**What this PR does / why we need it**:
Update README to add cmd for link checker

Fixes: #issues/576

2020-09-01 15:24 UTC, codificat reviewed
Some comments/questions.

Also, I doubt that this fixes #576, at least in its current form... this is an update to the README, while #576 is a CI issue, no?

2020-09-01 15:24 UTC, codificat commented on README.md
> +  touch Gemfile.lock && chmod 777
This command is incomplete: `chmod 777` what? `Gemfile.lock` I assume... what about `.jekyll-cache` though?

2020-09-01 15:24 UTC, codificat commented on README.md
> +  podman run -d --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll /bin/bash -c "bundle install ; rake";
This didn't work for me... I'm running on Fedora 32 with SELinux enabled and I had another pod run the jekyll server, so I guess permissions were owned by that one.

Besides that, I believe the `rake` invocation is incomplete. Shouldn't that be `rake links:test_external` ? or maybe even: `bundle exec rake links:test_external`

2020-09-01 15:24 UTC, codificat commented on README.md
> +- Verify internal and external hyperlinks
The other two items in this list are about running a local copy of jekyll to serve the website.

Shouldn't this ("how to verify links") go out of the list?

2020-09-01 15:48 UTC, codificat commented on README.md
> +  podman run -d --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll /bin/bash -c "bundle install ; rake";
FWIW this worked for me (I also switched from daemon mode to interactive, and added `--rm` as it's a one-off):

```
podman run --rm -i \
    --name linkcheck -v $(pwd):/srv/jekyll:Z jekyll/jekyll:latest \
    /bin/sh -c "bundle install && bundle exec rake links:test_external"
```

2020-09-01 17:33 UTC, mazzystr commented on README.md
> +  touch Gemfile.lock && chmod 777
...and this is why we have peer reviews!

2020-09-01 18:29 UTC, mazzystr commented on README.md
> +  podman run -d --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll /bin/bash -c "bundle install ; rake";
The procedure doesn't work for either one of us out of the box (without applying tribal knowledge) not even podman run to run the container and jekyll site.  I fixed this procedure once and for all...

2020-09-02 20:50 UTC, mazzystr commented on README.md
> +- Verify internal and external hyperlinks
Do you mean think we should ask the community if we should add this section?

2020-09-09 23:20 UTC, codificat commented on README.md
> +- Verify internal and external hyperlinks
Sorry I wasn't clear (and I missed the request for clarification).

No, I wasn't talking about asking the community. I'm referring to "indentation" here... let me try to elaborate.

`Verify internal and external hyperlinks` is proposed as a new list item on the existing list that covers two ways to run Jekyll (with or without SELinux).

To me, the "how to run Jekyll" list should be left alone, and the "Verify links" content should be separate - not as an item in the same list (a list of ways to run Jekyll to serve the website).

Makes sense?

2020-09-09 23:22 UTC, codificat commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.
I understand the idea and I like the simplification. I'm just wondering though: the longer content here ("be sure to cd into...") was meant to be a warning. If we strip that, should we replace **Note** with **Warning** ?

2020-09-11 20:35 UTC, mazzystr commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.
The cd cmd is forcibly added to L14. 

Can you show me another example of a project specifically calling out a warning for SELinux context change of files.  At some point knowledge of these kind of things are to be expected.  We're already adding with SELinux and without SELinux commands.  No one else on Docker Hub does this...at least not for the dozen containers especially [Ceph](https://github.com/ceph/ceph-container/tree/master/src/daemon).

2020-09-17 16:52 UTC, hroyrh reviewed
A few minor comments.

2020-09-17 16:52 UTC, hroyrh commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.  Be sure
... will relabel its contents so "that" it can be written .. 
extra space after the first line

2020-09-17 16:59 UTC, mazzystr commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.  Be sure
re "that" ... fixed.

What do you mean be "extra space after the first line"?  Do you mean remove the emptyline at L24?

2020-09-17 17:04 UTC, hroyrh commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.  Be sure
No, the extra space here -> ... yourself.'  'Be sure that ...

2020-09-17 17:18 UTC, mazzystr commented on README.md
> +  **NOTE**: The Z at the end of the volume (-v) will relabel its contents so it can be written from within the container, like running `chcon -Rt svirt_sandbox_file_t -l s0:c1,c2` yourself.  Be sure
Done!

2020-09-18 16:36 UTC, codificat requested changes
Just one final thing

2020-09-18 16:36 UTC, codificat commented on README.md
> +  podman run -it --rm --name kubevirtio -p 4000:4000 -v $(pwd):/srv/jekyll jekyll/jekyll /bin/bash -c "bundle install; rake";
The command has the same challenges with SELinux as the others. In my env, this doesn't work out of the box - it does if I add `:Z` to the volume

2020-09-18 16:57 UTC, codificat commented
/lgtm
/approve

2020-09-18 16:59 UTC, merged