Multiple Network Attachment with bridge CNI
kubevirt/kubevirt.github.io pull request #631
Opened 2020-09-23 08:11 UTC by qinqon

**What this PR does / why we need it**:
Add blog port post to do follow up on multi network connectivity blog post
but this time with bridge CNI instead of OVS, cluster-network-addons-operator
to install all the kubevirt network operators and kubernetes-nmstate to
configure the bridge at nodes.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

2020-09-23 08:12 UTC, qinqon commented
/test all

2020-09-23 08:12 UTC, qinqon commented
/test all

2020-09-23 15:02 UTC, mazzystr commented
Thank for the contribution!

/lgtm
/approve

2020-09-28 15:40 UTC, codificat commented
@qinqon thanks for working on this, please let us know when this is ready for review.

2020-09-29 06:18 UTC, qinqon commented
@codificat when finished network team will review this and then is all good to be published

2020-09-29 15:34 UTC, RamLavi requested changes
first pass, some syntax & typo changes

2020-09-29 15:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +that secondary NIC is created, it's using a container image that contains dhclient already.
`dhclient`-->`dhcpClient`

2020-09-29 15:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +$
this is colored red from some reason in the output, perhaps you could remove it if it's not necessary?

2020-09-30 07:41 UTC, phoracek requested changes
For me, the main point of this is to advertise all the components allowing you to configure secondary networks through the API. The user must see that it is simple and they don't need to understand networking magic to do that.

Unlike at the time of the previous blog post, now we have API for everything and it should be rather simple to get that going.

Because of that, I think we should keep this without getting into details of veth etc. We should configure bridge, setup NAD, have 2 VMs connected to it. And to have DHCP in the cluster, just create a dnsmasq Pod that will serve our VMs (no need to go into details there, just say it is to emulate DHCP). And maybe we can totally drop DHCP from the picture, I'm not sure it brings much value to basic users, they would not run it in prod anyway.

In short, we should treat this as the biggest advertisement for "easy to setup secondary L2 networks", rather than deep dive into all the aspects of it.

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At a previous [blog post]({% post_url 2018-09-12-attaching-to-multiple-networks %}) we described how to attach Virtual Machines to multiple interfaces connected to different networks using multus + o
I would not start the post by describing the (very very outdated) old one. You should sell that we will configure secondary network for VMs via Linux bridge. Deployment of all the components and configuration of host networking will be done through the API.

And as a note bellow it you can mention the old blog post, why it was problematic and why is it better now (no dependency and everything through the API).

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Introduction
Use second level titles ##. Now it uses the same style as the main title and it is slightly confusing (and titles are spanning multiple lines)

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This meta operator is a deviation of [cluster-network-operator](https://github.com/openshift/cluster-network-operator) covering kubevirt networking needs.
Again, this intro is interesting only for people that care about CNO or OpenShift. I'd start with the important part - it is an operator deploying components for advanced networking features (not only for) VM workloads.

In fact, I would not mention CNO at all since it is only for OpenShift.

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At this specific case the components that we are going to install are multus, linuxBridge and nmstate so the
linux bridge CNI.

And mention that you will explain all of them in detail later.

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This meta operator is a deviation of [cluster-network-operator](https://github.com/openshift/cluster-network-operator) covering kubevirt networking needs.
Mention why having an operator is great - you do everything through the API and you don't have to go over all nodes to install these components yourself. It also assures smooth updates.

This is our chance to get some new users.

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Bridging pods and nodes with bridge CNI
"bridging" may not mean anything to regular users. "Connecting Pods, VMs and Nodes over a single network" may be better (but I'm not 100% sure about that either)

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +As explained at previous blog is possible to add a secondary network interface to a pod using multus meta CNI and for that secondary interface is possible to specify what CNI to use, in this case we
Again, start with the interesting parts - why would you want to connect your components to a single L2 network if you already have the pod network. I don't want to think about the previous blogpost here.

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To do so a bridge is expected to be already created at Node since bridge CNI no longer creating it for you, to ensure that the configuration is applied only at pods on nodes that has the bridge the `
"no longer" would make sense only to people who remember it creating the bridge. Saying that the CNI only attaches to an existing bridge, and that's why you have to create it first, would be enough

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +until kubectl get crd kubevirts.kubevirt.io; do
I would vote to use single-line commands instead of writing scripts here. It is acceptable to ask the user to retry until it gets created - that's an easy human language, rather than having them read this bash magic

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +until kubectl -n kubevirt get kv kubevirt; do
ditto

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Wait for all the components to be deployed and ready
Please add : after each sentence describing a following code block

2020-09-30 07:41 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +  nmstate: {}
Consider including KMP as well. Our chance to advertise it

2020-10-05 08:21 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At a previous [blog post]({% post_url 2018-09-12-attaching-to-multiple-networks %}) we described how to attach Virtual Machines to multiple interfaces connected to different networks using multus + o
Done

2020-10-05 08:21 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Introduction
Done

2020-10-05 08:21 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This meta operator is a deviation of [cluster-network-operator](https://github.com/openshift/cluster-network-operator) covering kubevirt networking needs.
Done

2020-10-05 08:22 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At this specific case the components that we are going to install are multus, linuxBridge and nmstate so the
Done

2020-10-05 08:25 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This meta operator is a deviation of [cluster-network-operator](https://github.com/openshift/cluster-network-operator) covering kubevirt networking needs.
Done

2020-10-05 08:26 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Bridging pods and nodes with bridge CNI
Done

2020-10-05 08:38 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +As explained at previous blog is possible to add a secondary network interface to a pod using multus meta CNI and for that secondary interface is possible to specify what CNI to use, in this case we
Done

2020-10-05 08:38 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To do so a bridge is expected to be already created at Node since bridge CNI no longer creating it for you, to ensure that the configuration is applied only at pods on nodes that has the bridge the `
Done

2020-10-05 08:45 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +until kubectl get crd kubevirts.kubevirt.io; do
Well people is going to copy paste stuff and also they may end up scripting stuff, is not bad that we do the proper stuff here.

2020-10-05 08:45 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +until kubectl -n kubevirt get kv kubevirt; do
Ditto

2020-10-05 08:46 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Wait for all the components to be deployed and ready
ditto

2020-10-05 08:46 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +  nmstate: {}
ditto

2020-10-05 12:04 UTC, rhrazdil requested changes

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Also inspecting the full currentState yaml we will get the following
When inspecting the full... we get the following...

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +can be consumed at the node
on the node

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +First step is to install the `virtcl` command line tool to play with virtual machines:
virtctl

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now it's time for startup the VMIs they will run at different nodes so we can check external connectivity of
Now it's the time to startup the VMIs running on different nodes

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now let's create two VirtualMachineInstance at each node they will have one secondary NIC connected to br0 using the multus configuration for vlan 100.
`VirtualMachineInstance`s on easch node

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Wait for the two VMIs to be ready at the end
at the end -> eventually

2020-10-05 12:04 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +And to finis this we use `ping` command to check that vmia and vmib communication is working fine using 10.200.0.2 as
finish

2020-10-05 15:23 UTC, RamLavi requested changes
first pass, until `# Mixing it all together, fine grain VM to external world communication.`

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With linux bridge CNI + multus it's possible to create a secondary NIC at pods that will attach a port to a specific node L2 linux bridge (created by kubernetes-nmstate) so connecting a node secondar
`to the node specific one` not sure I understood what you meant here

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This is an example of the results from bridge-marker on nodes:
not sure what you mean by results. can you add the command to get this?

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Changing kubernetes cluster node networking can be done manually iterating over all the cluster nodes and making changes or using different automatization tools like ansible, but using just another k
still valid

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Changing kubernetes cluster node networking can be done manually iterating over all the cluster nodes and making changes or using different automatization tools like ansible, but using just another k
still valid

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +It works as a k8s DaemonSet running pods at all the cluster nodes and reconciling three different CRs, the [NodeNetworkConfigurationPolicy](https://raw.githubusercontent.com/nmstate/kubernetes-nmstat
perhaps make it a dotted list?
```
three different CRs:
* [NodeNetworkConfigurationPolicy](https://raw.githubusercontent.com/nmstate/kubernetes-nmstate/master/deploy/crds/nmstate.io_v1beta1_nodenetworkconfigurationpolicy_cr.yaml) to specify cluster node network desired configuration
* [NodeNetworkConfigurationEnactment](https://raw.githubusercontent.com/nmstate/kubernetes-nmstate/master/deploy/crds/nmstate.io_v1beta1_nodenetworkconfigurationenactment_cr.yaml) (nnce) to troubleshoot issues with nncp
* [NodeNetworkState](https://raw.githubusercontent.com/nmstate/kubernetes-nmstate/master/deploy/crds/nmstate.io_v1beta1_nodenetworkstate_cr.yaml) (nns) to view the node's networking configuration
```

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> There is already an issue related to clusters not having a default gw making the nncp always to rollback, there are plans to use different approach like checking name servers.
`There is already an issue`-->`There is a known issue` + maybe attach a link to the issue, if a BZ exist?

2020-10-05 15:23 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +What can be and what cannot be on a nncp desired state field depends on nmstate and it can be checked out at their [awesome doc|https://www.nmstate.io/]
wrong link syntax `[awesome doc|https://www.nmstate.io/]` -->`[awesome doc](https://www.nmstate.io/)`

2020-10-06 07:25 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +tittle: Multiple Network Attachment with bridge CNI
Done

2020-10-06 07:58 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides you with a default interfaces that gives connectivity to pods and VMs, it's not easy if not impossible to specify on a multi NIC node cluster which one should used for sp
The it would be a sub-title of Introducction, it just illustrate how the multus configuration is.

2020-10-06 08:00 UTC, alonSadan commented
Thanks Quique. I learned a lot

2020-10-06 08:01 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With linux bridge CNI + multus it's possible to create a secondary NIC at pods that will attach a port to a specific node L2 linux bridge (created by kubernetes-nmstate) so connecting a node secondar
I don't understand the whole paragraph... I will rewrite it.

2020-10-06 08:06 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> The architecture of kubernetes-nmstate is fully distributed to reduce the kube-apiserver connectivity dependency since playing around with node networking can break that, this means that every pod
reworded

2020-10-06 08:18 UTC, alonSadan commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> note "Note"
The notes still looks weird. https://github.com/kubevirt/kubevirt.github.io/blob/592b924cfec39241bafbb24d883a33839172cf91/_posts/2020-09-23-attaching-to-multiple-networks-followup.markdown

I think something like that will work:
```
> **Note:** 
> Project kubernetes-nmstate has a distributed architecture to reduce kube-apiserver connectivity dependency, this means that every pod will configure the networking on the node that it's running without much interaction with kube-apiserver.
```

2020-10-06 08:24 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> note "Note"
They look fine at preview version https://deploy-preview-631--kubevirtio.netlify.app/2020/attaching-to-multiple-networks-followup.html

2020-10-06 09:10 UTC, alonSadan commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> note "Note"
oh great!

2020-10-06 09:34 UTC, RamLavi requested changes
This blog is very good, please attach it to the CNV-network on-boarding document when it's published

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a pair virtual machines on two different nodes with three secondary NIC, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200, they will be connected to each ot
`with a pair virtual machines` --> `with a pair of virtual machines`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a pair virtual machines on two different nodes with three secondary NIC, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200, they will be connected to each ot
`three secondary NIC,`-->`three secondary NICs,`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a pair virtual machines on two different nodes with three secondary NIC, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200, they will be connected to each ot
`200, they will`-->`200. They will`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> In case of errors is possible to retrieve the error dumped by nmstate running
`In case of errors is possible to retrieve`-->`In case of errors it is possible to retrieve`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +It needs to specify the br0 as the port no ipam to make it L2 bridge and
not sure what is `It` here.
I would reword to something like "In order to make the bridge a L2 bridge with vlan, we ..."

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +## Start a pair of VMI at different nodes using the multus configuration to connect a secondary interfaces to br0
` VMI at different `-->` VMI on different `

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now it's the time to startup the VMIs running on different nodes so we can check external connectivity of
`Now it's the time to`-->`Now it's time to`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +br0, they will also have a secondary NIC eth1 to connect to the other VM running at different node, so they go
`, they will also` break to new sentence `.  They will also`

2020-10-06 09:34 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now we start up those interfaces assign ip addresses and add routes to them.
`Now we start up those`-->`Now to start up those`

2020-10-06 09:52 UTC, rhrazdil requested changes

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To ensure that the configuration is applied only in pods on nodes that have the bridge the `k8s.v1.cni.cncf.io/resourceName` is added, this goes hand in hand with another component [bridge-marker](ht
```suggestion
To ensure the configuration is applied only in pods on nodes that have the bridge, the `k8s.v1.cni.cncf.io/resourceName` label is added. This goes hand in hand with another component, [bridge-marker](https://github.com/kubevirt/bridge-marker) which inspects nodes networking and if a new bridge pops up it will mark the node status with it.
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Changing kubernetes cluster node networking can be done manually iterating over all the cluster nodes and making changes or using different automatization tools like ansible, but using just another k
Just an idea. Up to you to consider, relates to the following line
```suggestion
Changing kubernetes cluster node networking can be done manually iterating over all the cluster nodes and making changes or using different automatization tools like ansible, but using just another kubernetes resource is more convenient.
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +make it very convenient, for this the kubernetes-nmstate project was born as a cluster wide node network administrator based on kubernetes CRs on top of [nmstate](https://github.com/nmstate/nmstate).
```suggestion
For this purpose the kubernetes-nmstate project was born as a cluster wide node network administrator based on kubernetes CRs on top of [nmstate](https://github.com/nmstate/nmstate).
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Also for more details on kubernetes-nmstate there are guides covering [reporting](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-101-reporting.md), [configuration](https://
```suggestion
Also for more details on kubernetes-nmstate there are guides covering [reporting](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-101-reporting.md), [configuration](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-102-configuration.md) and [troubleshooting](https://github.com/nmstate/kubernetes-nmstate/blob/master/docs/user-guide-103-troubleshooting.md). There are also [nncp examples](https://github.com/nmstate/kubernetes-nmstate/tree/master/docs/examples).
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a pair virtual machines on two different nodes with three secondary NIC, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200, they will be connected to each ot
```suggestion
With the following recipe we will end up with a pair of virtual machines on two different nodes with three secondary NICs, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200, they will be connected to each other using
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now we wait for the bridge to be created checking nncp conditions
```suggestion
Now we wait for the bridge to be created checking nncp conditions:
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In case that our cluster has multiple nodes we can inspect the status applying the policy
```suggestion
We can inspect the status of applying the policy to each node.
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +to each node for that we have the NodeNetworkConfigurationEnactment or nnce
```suggestion
For that there is the NodeNetworkConfigurationEnactment CR (nnce):
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can also inspect the network state on the nodes retrieving the NodeNetworkState and
```suggestion
We can also inspect the network state on the nodes by retrieving the NodeNetworkState and
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +check if the bridge `br0` is up using jsonpath
```suggestion
checking if the bridge `br0` is up using jsonpath
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can also check that the `bridge-marker` is working and check resources at nodes
```suggestion
We can also check that the `bridge-marker` is working and check resources on nodes
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +can be consumed on the node
```suggestion
can be consumed on the node:
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At this point we have ready L2 linux bridge connected to NIC eth1
```suggestion
At this point we have ready L2 linux bridge connected to NIC eth1.
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +It needs to specify the br0 as the port no ipam to make it L2 bridge and
I would suggest starting this section with some introductory sentence, like: To achieve `this` and `that` with the linux bridge, we create a net-attach-def. The net-attach-def needs to specify ....

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +you will get something like this
```suggestion
you will get something like this:
```

2020-10-06 09:52 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +address assigned
```suggestion
address assigned:
```

2020-10-06 10:18 UTC, rhrazdil reviewed
One more note, we should probably use KubeVirt with capital 'K' and 'V' in the text

2020-10-07 12:36 UTC, qinqon commented
force-push: Addressed Ram's comments

2020-10-07 13:02 UTC, qinqon commented
force-push: Addressed Radim's comments

2020-10-08 09:34 UTC, rhrazdil requested changes

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +this progress we can query the CR status with the following command
```suggestion
this progress we can query the CR status with the following command:
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides you with a default interfaces that gives connectivity to pods and VMs, it's not easy if not impossible to specify on a multi NIC node cluster which one should be used for
```suggestion
Although kubernetes provides a default interface that gives connectivity to pods and VMs, it's not easy, if not impossible, to configure which NIC should be used for specific pods or VMs in a multi NIC node cluster. Typical use case is to split control/traffic planes isolated by different NICs on nodes.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +It works as a k8s DaemonSet running pods at all the cluster nodes and reconciling three different CRs:
```suggestion
It works as a k8s DaemonSet running pods on all the cluster nodes and reconciling three different CRs:
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In case something goes wrong and the pod changing the node network cannot ping the default gateway or has lost the kube-apiserver connectivity it will rollback to the previous configuration to go bac
Just an idea, if you don't like this change, I would only suggest to split the sentences

```suggestion
In case something goes wrong and the pod changing the node network cannot ping the default gateway or has lost the kube-apiserver connectivity it will rollback to the previous configuration to go back to a working state. Those errors can be checked by running `kubectl get nnce`. The command displays potential issue per node and nncp.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +the same bridge at nodes that also has the external secondary NIC eth1 connected.
```suggestion
the same bridge on nodes that also have the external secondary NIC eth1 connected.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We are going to use a [kubevirtci](https://github.com/kubevirt/kubevirtci) as kubernetes ephemeral cluster provider
```suggestion
We are going to use a [kubevirtci](https://github.com/kubevirt/kubevirtci) as kubernetes ephemeral cluster provider.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To start it up with two nodes and one secondary NIC and install NetworkManager >= 1.22 (needed for kubernetes-nmstate) and dnsmasq follow the following steps:
```suggestion
To start it up with two nodes and one secondary NIC and install NetworkManager >= 1.22 (needed for kubernetes-nmstate) and dnsmasq follow these steps:
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +After that if we query the nncp in the cluster we should get that we
```suggestion
After the nncp becomes available, we can query the nncp resources in the cluster
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +have one and status is ok.
```suggestion
and see it listed with successful status.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> `kubectl get nnce -o yaml` the status will print the error.
```suggestion
> `kubectl get nnce -o yaml` the status will contain the error.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can also check that the `bridge-marker` is working and check resources on nodes
```suggestion
We can also check that the `bridge-marker` is working and check resources on nodes:
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +and under status something like the following should appear stating that br0
```suggestion
The following should appear stating that br0
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Wait for the two VMIs to be ready eventually
```suggestion
Wait for the two VMIs to be ready.
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +you will get something like this:
```suggestion
Eventually you will see something like this:
```

2020-10-08 09:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now we to start up those interfaces assign ip addresses and add routes to them.
```suggestion
In the next step we assign them with ip addresses, set them up and configure routing rules.
```

2020-10-08 09:49 UTC, maiqueb reviewed
Just some remarks.

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides you with a default interfaces that gives connectivity to pods and VMs, it's not easy if not impossible to specify on a multi NIC node cluster which one should be used for
'a default interface', singular.

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides you with a default interfaces that gives connectivity to pods and VMs, it's not easy if not impossible to specify on a multi NIC node cluster which one should be used for
I would outright remove the 'if not impossible' part, it only confuses the reader.

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +    bridge.network.kubevirt.io/testBridge: 1k
I'd have this match the `resourceName` requested below - br0 .

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +## Messing up node networking with NodeNetworkConfigurationPolicy (aka nncp)
I'd replace the 'messing up' part w/ 'setting up' / 'configuring'. Who would want to 'mess up their networking' ?

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +What can be and what cannot be in a nncp desired state field depends on nmstate and it can be checked out at their [awesome doc](https://www.nmstate.io/)
This line does not read well; "The desired state field follow the nmstate API described @ ... " ?

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Mixing it all together, fine grain VM to external world communication
I don't get the 'fine grain' part. What do you intended with that ?

2020-10-08 09:49 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a virtual machines pair on two different nodes with three secondary NICs, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200. They will be connected to each o
I'd have a short list instead, something like:
```
In this section we will show the configuration to achieve our goal, which is to have one VM in each node, whose config is:
  - eth1; no vlan
  - eth2; vlan 100
  - eth3; vlan 200

...
```

2020-10-08 10:19 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Mixing it all together, fine grain VM to external world communication
Removing it.

2020-10-08 10:22 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a virtual machines pair on two different nodes with three secondary NICs, eth1 no vlan, eth2 vlan 100 and eth3 vlan 200. They will be connected to each o
This is old at the end I just configured one secondary nic to communicate will reworkd this.

2020-10-08 12:56 UTC, maiqueb requested changes

2020-10-08 12:56 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To simplify this blog post we are going to use directly the NetworkAddonsConfig from HCO, which by default installs all the network components, but just to illustrate CNAO configuration, the followin
You're only mentioning kubemacpool here, and not referring to it in any example below. What's the point ?... Since it's not used for anything, omit it.

And the 'following' is not a "NetworkAddonsConfig CR instructing to deploy multus, linuxBridge, nmstate and kubemacpool components". Kubemacpool is not there.

2020-10-08 12:58 UTC, qinqon commented
Fixed ip addresses on VMIs

2020-10-08 13:01 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To simplify this blog post we are going to use directly the NetworkAddonsConfig from HCO, which by default installs all the network components, but just to illustrate CNAO configuration, the followin
it's for marketing purposes :D https://github.com/kubevirt/kubevirt.github.io/pull/631#discussion_r497302759

2020-10-08 13:17 UTC, RamLavi requested changes
looks really good. 
we could benefit with a small chart showing the players we create in this blog.

2020-10-08 13:17 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides a default interface that gives connectivity to pods and VMs, it's not easy, to configure which NIC should be used for specific pods or VMs in a multi NIC node cluster. Ty
`it's not easy, to`--> drop the `,` `it's not easy to`

2020-10-08 13:17 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +over the br0 at nodes.
suggestion, maybe add box chart showing the components and how they are connected? 
should be 2 nodes, each having a vm, connected to the node bridge br0 via net1?

2020-10-08 13:28 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +over the br0 at nodes.
Will try it.

2020-10-08 15:20 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +## Start a pair of VMI on different nodes using the multus configuration to connect a secondary interfaces to br0
```suggestion
## Start a pair of VMIs on different nodes using the multus configuration to connect a secondary interfaces to br0
```

2020-10-08 15:20 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can check that they have one secondary NIC without
Are the IP addresses not showing up because there isn't guest agent installed?
If so, it may be worth adding a note explaining this

2020-10-08 15:20 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +And to finish this we use `ping` command to check that vmia and vmib communication is working fine using 10.200.0.2 as
```suggestion
Let's finish this section by verifying connectivity between vmia and vmib using `ping`. Open the console of vmia virtual machine and use `ping` command with destination IP address 10.200.0.2, which is the address assigned to the secondary interface of vmib:
```

2020-10-08 15:20 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +destination since is the address that vmib has at its eth1 interface:
```suggestion
```

2020-10-08 15:20 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +```
It may be nice to add a Conclusion section, where you could summarize what we used, what we achieved and what is it good ofr

2020-10-13 07:56 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can check that they have one secondary NIC without
Yep that's it, I will add a note.

2020-10-13 08:01 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can check that they have one secondary NIC without
I think @rhrazdil is right:  the lack of IP addresses comes from the missing guest agent (all binding types - except masquerade rely on the guest-agent iirc).

I also agree that since you mention the IP is missing, you might as well write why. I think it is also OK to just omit the entire  paragraph.

2020-10-13 10:14 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +over the br0 at nodes.
Added a graphviz diagram.

2020-10-13 10:15 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can check that they have one secondary NIC without
Added some steps to install the guest aggent

2020-10-13 11:38 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +To simplify this blog post we are going to use directly the NetworkAddonsConfig from HCO, which by default installs all the network components, but just to illustrate CNAO configuration, the followin
Now the `default` namespace has the opt-in for kubemacpool so VMIs use it, I also add some description before the VMIs manifests.

2020-10-13 11:48 UTC, phoracek requested changes

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +```bash
Would you set highlighting to yaml? Since most of the snippet is yaml, it may be more readable.

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +```bash
Please set the syntax to yaml instead

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Mixing it all together, VMI to VMI communication between nodes
We should start on second level header to match the format used above, no? If we make it level 1, it looks like the header of the whole blogpost (and takes way too much space)

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +category: news
This is not really news, is it?

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +# Mixing it all together, VMI to VMI communication between nodes
Also, would you prefix it with "Demo:" maybe? So it is clear that from now on, it is all for copy pasting.

2020-10-13 11:48 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +$kubectl get nncp
Issue of this style of "command line examples" is that you cannot triple-click the line to highlight and copy it and just paste it to terminal. There is also "Copy" button that cannot be used with this. Consider following:

```shell
kubectl get nncp`
```

```
NAME       STATUS
br0-eth1   SuccessfullyConfigured
```

2020-10-13 12:35 UTC, RamLavi commented
/lgtm

2020-10-13 12:37 UTC, merged

2020-10-13 12:40 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +through a linux bridge connected to a secondary NIC, this illustrate how VM traffic can be connected to a specific NIC
... secondary NIC. This illustrate**s** ...

2020-10-13 12:40 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +at node using a secondary NIC.
**on a** node using a secondary node NIC.

2020-10-13 12:41 UTC, phoracek commented
We should revert this ASAP. @qinqon  would you open a PR real quick so we don't keep the unfinished post published?

2020-10-13 12:42 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +{% endgraphviz %}
Shouldn't this be correctly indented ? Half of it is wrong (I could even buy 'all wrong'... ).

2020-10-13 12:42 UTC, maiqueb commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +nd_eth1_vmia [label = "eth1"];
All interfaces in the graph are named  `eth1`. Sounds confusing.

2020-10-13 15:55 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +nd_eth1_vmia [label = "eth1"];
We have a eth1 at node and at eth1 at VMIs there is nothing we can do about it.

2020-10-13 15:56 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +{% endgraphviz %}
I think repo post-commit tooling if being too smart here.