Create Makefile.  Create casperjs test script.  Update Rakefile for a…
kubevirt/kubevirt.github.io pull request #636
Opened 2020-10-12 21:49 UTC by mazzystr

**What this PR does / why we need it**:
Re Makefile ... See user-guide [comment](https://github.com/kubevirt/user-guide/issues/359#issuecomment-700810450) for list on what this Makefile needs to do
RE .yaspeller file ... big update to consolidate and do better
RE casperjs test script ... this script takes in a url and file csv pair and tests the presence of the selector
RE Rakefile ... Update to add test cases for website to userguide links

**Does this PR fix any issue?** 
> Fixes #634 
> Fixes #576 

NOTES: See user-guide [issues/#359](https://github.com/kubevirt/user-guide/issues/359) for notes driving this pull request.

2020-10-15 23:49 UTC, mazzystr commented
This PR is ready for reviewing

@fabiand @rmohr  I would love input is you have minutes to spare

2020-10-19 08:19 UTC, rmohr commented
@mazzystr looks good to me in general. I guess it would make sense if @codificat reviews and merges this. Thanks for the work.

2020-10-20 18:50 UTC, codificat requested changes
Reviewed/tested live and some issues were found with container permissions in the run-* targets.

Besides these, just one minor comment so far

2020-11-02 19:41 UTC, codificat commented
I tried to run `make checks` ane I'm getting some permission errors, e.g.

```sh
$ make check_spelling_kubevirtio

Makefile: Check kubevirtio spelling
podman run -it --rm --name yaspeller --net=host -v /scratch/git/kubevirt/website:/srv"" -v /scratch/git/kubevirt/project-infra/images/yaspeller/.yaspeller.json:/srv/.yaspeller.json"" yaspeller /bin/bash -c "echo; yaspeller -c /srv/.yaspeller.json --only-errors --ignore-tags iframe,img,code,kbd,object,samp,script,style,var /srv" | \
sed -e 's/\/srv/\./g'

Error: EACCES: permission denied, open './.yaspeller.json'
```

This seems to be SELinux:

```sh
$ ausearch -m avc -ts recent
----
time->Mon Nov  2 20:20:35 2020
type=AVC msg=audit(1604344835.587:339): avc:  denied  { read } for  pid=22903 comm="node" name=".yaspeller.json" dev="dm-0" ino=1701018 scontext=system_u:system_r:container_t:s0:c329,c623 tcontext=unconfined_u:object_r:default_t:s0 tclass=file permissive=0
```

2020-11-04 19:11 UTC, mazzystr commented
/hold

2020-11-11 00:00 UTC, mazzystr commented on .travis.yml
>  - npm install -g yaspeller
I would love too update Travis to use the new container but just not right this sec.  We need to crawl and walk before running.  I was having a problem with rake and ruby maps and thought the version mismatch might have been behind the it.  It wasn't.  It's just ruby doing what ruby does.

It's a nonchanging change.  I'm happy to back this diff out.

2020-11-11 00:04 UTC, mazzystr commented
> ```shell
> -v /scratch/git/kubevirt/website:/srv""
> ```

notice...
`-v /scratch/git/kubevirt/website:/srv""`

SELinux is not set 

Try...
`export SELINUX_ENABLED=True; make check_links_website`

Also note that I removed the `checks` target to clarify functionality.

2020-12-01 20:09 UTC, mazzystr commented
We're getting close to this pull being mergable.  Three more items need to be addressed....

* spellchecker ... spellchecker has empty output on success.  I need to add a complete! msg
* spellchecker .... retval is always 0 due to `cmd | sed` and `echo`.  The echo can be removed since it's cosmetic.  The sed is helpful to identify exactly what file is having the problem.  Since we're doing containers the file path gets changed to the container env and that's reflected in output.  We need to sed to munge the path back.  In the course of doing so we're losing the return code.
* debug mode ... Makefile echo each rule line by default.  Some of the rules/cmds are really long and make runnning a Makefile target obnoxious.  I like seeing them because we can copy/paste directly into cmdline to debug. I'm seek a happy medium and add a hidden debug mode to trigger verbose rule/cmd output.

2020-12-04 17:10 UTC, mazzystr commented
@codificat I'd say we're ready for merge once CI completes

2020-12-07 20:46 UTC, codificat commented
/retest

2020-12-14 19:42 UTC, mazzystr commented
Stand by for user-guide link fix in another pull req then rebase.

2020-12-16 14:18 UTC, codificat commented
With the latest changes, spell checking is now failing for me (IIRC it was working before):

```sh
$ make check_spelling_userguide

Makefile: Check userguide spelling
Error: /scratch/git/kubevirt/user-guide/docs:/srv/docs:Z:ro: incorrect volume format, should be [host-dir:]ctr-dir[:option]
Complete!
$ make check_spelling_website

Makefile: Check website spelling
Error: /scratch/git/kubevirt/website:/srv:Z:ro: incorrect volume format, should be [host-dir:]ctr-dir[:option]
Complete!
```

2020-12-17 07:02 UTC, mazzystr commented
@codificat SELinux enforcing/permissive confirmed for check/run/stop/build targets.  This is going to need to be something we should CI/CD in the near future.  It was really painful to test everything.

2020-12-17 15:20 UTC, codificat commented
/lgtm
/approve

2020-12-17 15:22 UTC, merged