Attaching to multiple networks followup 2
kubevirt/kubevirt.github.io pull request #638
Opened 2020-10-13 12:54 UTC by qinqon

**What this PR does / why we need it**:
Multiple Network Attachment with bridge CNI (#631)
    
Add blog port post to do follow up on multi network connectivity blog post
but this time with bridge CNI instead of OVS, cluster-network-addons-operator
to install all the kubevirt network operators and kubernetes-nmstate to
configure the bridge at nodes.
    
It also install jekyll-diagrams [1]
    
[1] https://github.com/zhustec/jekyll-diagrams

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:
Depends on https://github.com/kubevirt/kubevirt.github.io/pull/637

2020-10-13 12:57 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
>  pub-date: September 23
Bring this up to date, so it appears last in the list of blog posts

2020-10-13 15:06 UTC, maiqueb requested changes
Please take the opportunity to also address:
  - https://github.com/kubevirt/kubevirt.github.io/pull/631#discussion_r503913074
  - https://github.com/kubevirt/kubevirt.github.io/pull/631#discussion_r503918324

2020-10-15 09:45 UTC, RamLavi requested changes
we need to change to vms instead of vmis.
KMP allocates mac to vmis via the pod webhook and we currently have a bug there + it's not opted in. plus it's better practice to use vms...

2020-10-15 09:45 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now let's create two VirtualMachineInstances on each node they will have one secondary NIC connected to br0 using the multus configuration for vlan 100, also activate kubemacpool to be sure that mac
```suggestion
Now let's create two VirtualMachineInstances on each node they will have one secondary NIC connected to br0 using the multus configuration for vlan 100. We will also activate kubemacpool to be sure that mac addresses are unique in the cluster and install the qemu-guest-agent so ip addresses from secondary NICs are reported to VMI and we can inspect them later on.
```

2020-10-15 09:45 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +kind: VirtualMachineInstance
if you want KMP to work you need to run vms, not vmis.

2020-10-15 09:45 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +    mac: ae:2a:27:59:02:04
notice the macs allocated on `eth0`, `eth1` are not on same range

2020-10-15 12:15 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +The desired state field follow the nmstate API described at their [awesome doc](https://www.nmstate.io/)
```suggestion
The desired state fields follow the nmstate API described at their [awesome doc](https://www.nmstate.io/)
```

2020-10-15 12:15 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can also check that the `bridge-marker` is working and check resources on nodes:
just think that this may sound a bit better
```suggestion
We can also check that the `bridge-marker` is working and check verify on nodes:
```

2020-10-19 13:17 UTC, qinqon commented
Pushed:
* Addressed Radim and Ram comments
* Fixed set-context issue with deploy.sh from HCO
* Pod network binding set to masquerade since it's the default binding configured at HCO if no interface is specified.

2020-10-19 13:20 UTC, qinqon commented
Push:
* Fixed VMs interface output now that MAC address comes from kubemacpool.

2020-10-19 13:47 UTC, RamLavi requested changes

2020-10-19 13:47 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +he desired state fields follow the nmstate API described at their [awesome doc](https://www.nmstate.io/)
```suggestion
The desired state fields follow the nmstate API described at their [awesome doc](https://www.nmstate.io/)
```

2020-10-19 13:47 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +## Demo: mixing it all together, VMI to VMI communication between nodes
```suggestion
## Demo: mixing it all together, VM to VM communication between nodes
```

can you also do a sweep and make sure `vmi` is not used when `vm` should be?

2020-10-19 13:47 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +  name: vma
do we want to set explicit namespace to avoid HCO setting it on HCO's default ns?

2020-10-19 14:37 UTC, qinqon commented
Push:
* Addressed Ram's comments

2020-10-19 14:57 UTC, RamLavi commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +apiVersion: nmstate.io/v1alpha1
shouldn't it be [v1beta1](https://github.com/nmstate/kubernetes-nmstate/blob/master/deploy/crds/nmstate.io_nodenetworkconfigurationpolicies.yaml)?

2020-10-20 08:26 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +apiVersion: nmstate.io/v1alpha1
Nope, latest released CNAO does not has that yet, https://github.com/kubevirt/cluster-network-addons-operator/blob/v0.42.2/data/nmstate/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml.

2020-10-20 08:28 UTC, RamLavi commented
/lgtm

2020-10-20 08:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At this blog post we used some network components from kubevirt project to communicate two VMs at different nodes
In this blog post we used network components from kubevirt project to connect two VMs on different nodes

2020-10-20 08:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +through a linux bridge connected to a secondary NIC, this illustrate how VM traffic can be connected to a specific NIC
through a linux bridge connected to a secondary NIC. This illustrates how VM traffic can be directed to a specific NIC

2020-10-20 08:34 UTC, rhrazdil commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +at node using a secondary NIC.
on a node using a secondary NIC on a VM.

2020-10-20 09:13 UTC, phoracek requested changes

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This is an example of NetworkAttachmentDefinition to create a L2 bridge
It does not create a bridge, it exposes the bridge available on the host to users

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This is an example of the results from bridge-marker on nodes:
"on nodes where bridge br0 is already configured"

So it is clear that somebody needs to manage them. And in the next section you describe how.

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +      ipv4:
Can we drop this if it is not used? And if not, we should be able to drop at least the dhcp part since we set it to disabled anyway.

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +### Configure multus attachment with a L2 bridge and a vlan
It is a network attachment. Multus just happens to be an implementation of this "de-facto standard"

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +The following picture illustrate the cluster:
illustrates

2020-10-20 09:13 UTC, phoracek commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +64 bytes from 10.200.0.2: seq=0 ttl=50 time=357.040 ms
Are we really getting this horrible latency?

2020-10-20 10:31 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +category: uncategorized
we have: `releases`, `updates`, `news` and `uncategorized`, they are pretty general categories maybe `updates` will fit ?

2020-10-20 10:36 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +64 bytes from 10.200.0.2: seq=0 ttl=50 time=357.040 ms
Well this is two nodes kubevirtci at my laptop.

2020-10-20 10:37 UTC, qinqon commented
Adressed Radim's comments.

2020-10-20 10:38 UTC, qinqon commented
Adressed Petr's comments.

2020-10-20 10:44 UTC, rhrazdil commented
@qinqon Looks good to me

2020-10-20 10:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +category: uncategorized
For now please use `news`. While it doesn't really fit, it's what blog posts have been using...

We will improve this once issue #510 gets addressed

2020-10-21 09:05 UTC, qinqon commented
@codificat moved it to `news`

2020-10-21 09:14 UTC, phoracek commented
/lgtm

Thanks, awesome!

2020-10-21 11:54 UTC, codificat requested changes
Great post, thanks!

Only a few minor comments around syntax/grammar mostly.

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +pub-date: October 13
Can you update this to `October 21` and rename the file to `2020-10-21-attaching...` accordingly please? Otherwise it appears as published on Sept 23rd

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Over the last years KubeVirt project has improved a lot regarding secondary interfaces networking configuration. Now it's possible to do an end to end configuration from host networking to a VM using
_the_ KubeVirt project

and _Kubernetes_ (capital K)

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +special CRDs. Moreover, the deployment of all the projects has been simplified by introducing [kubevirt hyperconverged cluster operator (HCO)](https://github.com/kubevirt/hyperconverged-cluster-opera
_KubeVirt_ (camel case) hyperconverged...

Also it's probably worth expanding the acronym _Custom Resource Definitions (CRDs)_ even if it's quite common these days.

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Good thing about having an operator is that everything is done through the API and you don't have to go over all nodes to install these components yourself and assures smooth updates.
_A_ good thing, or _The_ good thing it you prefer

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +configure secondary interfaces, manages MAC addresses and defines networking on hosts for pods and VMs.
_manage_ [...] _define_  without the "s", for sentence coherence and also because it's not CNAO who does that but the components it installs (right?)

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +The list of components we want CNAO to deploy is specified by the NetworkAddonsConfig CR and the progress of the installation appears in the CR status field, split per component. To inspect
First use acronym expansion: _Custom Resource (CR)_

Also we normally backtick `NetworkAddonsConfig` for formatting of code-like references

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Although kubernetes provides a default interface that gives connectivity to pods and VMs, it's not easy to configure which NIC should be used for specific pods or VMs in a multi NIC node cluster. Typ
*K*ubernetes.

_A_ typical use case

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +This is an example of NetworkAttachmentDefinition to exposes the bridge available on the host to users:
Backtick `NetworkAttachmentDefinition`

Also: _to expose_ (without "s")

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Then adding bridge secondary network to a pod is a matter of adding the following annotation to
Then adding _the_ bridge...

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Changing kubernetes cluster node networking can be done manually iterating over all the cluster nodes and making changes or using different automatization tools like ansible. However, using just anot
*K*ubernetes (x3)

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +It works as a k8s DaemonSet running pods on all the cluster nodes and reconciling three different CRs:
s/k8s/Kubernetes/

`DaemonSet`

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In case something goes wrong and the pod changing the node network cannot ping the default gateway or has lost the kube-apiserver connectivity it will rollback to the previous configuration to go bac
potential issue*s* (missing s)

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> There is a known issue related to clusters not having a default gateway making the nncp always to rollback, there are plans to use different approach like checking name servers.
Are there links available to the issue / plans?

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +With the following recipe we will end up with a virtual machines pair on two different nodes with one secondary NICs, eth1 at vlan 100. They will be connected to each other using
... end up with a pair of virtual machines ...

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +### Requirements
Are these real requirements? I think they are not (e.g. kubevirtci is used for illustration purposes)... so I would remove that headline, or better change it to something like "demo environment setup" to make it more clear

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +For that there is the NodeNetworkConfigurationEnactment CR (nnce):
Backtick `NodeNetworkConfigurationEnactment`

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +We can also inspect the network state on the nodes by retrieving the NodeNetworkState and
Backtick `NodeNetworkState` and maybe add "(nns)" next to it

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +At this point we have ready L2 linux bridge connected to NIC eth1.
... we have an L2 linux bridge ready and connected...

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In order to make the bridge a L2 bridge with vlan, we specify no ipam and
Something is unclear in that sentence, at least to me... could you expand it a bit to help clarify?

Besides that, *IPAM* (capitals for acronym) also probably deserves expansion and/or claritication... why does (no) IPAM apply to the VLAN case and it doesn't it there is no VLAN?

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +Now let's create two VirtualMachines on each node they will have one secondary NIC connected to br0 using the multus configuration for vlan 100. We will also activate kubemacpool to be sure that mac
Backtick `VirtualMachine`s.
Missing period (.) to separate sentences: ... on each node. They will...

Also *IP* (capitals)

2020-10-21 11:54 UTC, codificat commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In this blog post we used network components from kubevirt project to connect two VMs on different nodes
... from *the KubeVirt* project...

2020-10-21 12:57 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +> There is a known issue related to clusters not having a default gateway making the nncp always to rollback, there are plans to use different approach like checking name servers.
We have just merge the fix https://github.com/nmstate/kubernetes-nmstate/pull/606, I will remove the note.

2020-10-21 13:08 UTC, qinqon commented on _posts/2020-09-23-attaching-to-multiple-networks-followup.markdown
> +In order to make the bridge a L2 bridge with vlan, we specify no ipam and
Splitted at two stences one for L2 and the other for vlan, since IPAM and VLAN has no relation.

2020-10-21 13:11 UTC, qinqon commented
push: Addressed @codificat comments

2020-10-21 13:43 UTC, codificat commented
Great, thanks!
/approve

2020-10-21 13:44 UTC, codificat commented
oh, and
/lgtm

2020-10-21 13:45 UTC, merged