Add Monitoring KubeVirt VMs from the inside blog post
kubevirt/kubevirt.github.io pull request #641
Opened 2020-10-21 21:52 UTC by ArthurSens

Signed-off-by: arthursens <arthursens2005@gmail.com>

**What this PR does / why we need it**:
This PR adds a new blog post `Monitoring KubeVirt VMs from the inside`. Where it shows how to install KubeVirt, CDI, and Prometheus-Operator in a minikube cluster (Without any configuration changes in those components), then how to create a VM with persistent storage, how to access its console with virtctl, how to install node-exporter and, at last, how to expose the node-exporter's metrics endpoint to Prometheus.

**Special notes for your reviewer**:
Please try this guide yourself and see if it works for you as it did for me :slightly_smiling_face: 
The original content was written on one of public repos: https://github.com/ArthurSens/kubevirt-VM-monitoring

Over there you will find all YAML manifests and shell scripts to run this entire guide automatically

2020-10-21 21:57 UTC, ArthurSens commented on _posts/2020-10-21-KubeVirt-With-Prometheus.md
> +      summary: KubeVirt VM {{ $labels.pod }} is down.
How can I scape `{{ $labels.pod }} `?

2020-10-22 15:35 UTC, codificat commented on _posts/2020-10-21-KubeVirt-With-Prometheus.md
> +      summary: KubeVirt VM {{ $labels.pod }} is down.
You can use: `{%raw%}{{ $labels.pod }}{%endraw%}`

Not sure it there's a better way, but this should work.

2020-10-22 15:36 UTC, codificat commented
Build is failing due to an internal link. The anchor generated by Jekyll is: `configuring-prometheus-to-scrape-the-vms-node-exporter` (all lowercase, and removing the quote character)

2020-10-22 19:26 UTC, ArthurSens commented
I think all typos were fixed, and so was the internal link. Anything else I should be doing?

And it would be good if someone else followed the guide to make sure it is a valid one :slightly_smiling_face:

2020-11-02 22:51 UTC, mazzystr requested changes

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +```
Could you do me a favor and review `Deploy KubeVirt` at https://kubevirt.io/quickstart_minikube and let me know which way would be more preferrable.  I would really like to preset a single method of deploying KubeVirt.

I can update the quickstart guides if we prefer the method detailed in L60-81

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +We will start with the PersistenVolumes required by [CDI’s DataVolume](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md) resources. Since I’m using minikube with
It's `PersistentVolume`'s

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +We will start with the PersistenVolumes required by [CDI’s DataVolume](https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md) resources. Since I’m using minikube with
...and PVs

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +Notice that KubeVirt's VirtualMachine resource has a virtual machine template and a dataVolumeTemplate. On the virtual machine template, it is important noticing that we named our VM `monitorable-vm`
sed e 's/has a virtual machine template/has a VirtualMachine/g'

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +```
Please add a simple Conclusion.  An example is here ... https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html

2020-11-02 22:51 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +pub-date: October 21
My apologies for the lateness in review.  Please update the date.  Adjust the file name as well.

2020-11-02 22:52 UTC, mazzystr commented
@ArthurSens Fix a few nitpicks and this blog post will be ready for publishing.  Thank you for this contribution.

2020-11-03 11:05 UTC, codificat commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +```
Isn't it the same way? i.e. 1) deploy the operator 2) create the CR

(the "in-depth" way in the minikube quickstart, as the minikube addon way is obviously only available within minikube)

2020-11-03 17:14 UTC, ArthurSens commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +```
Yeah, this is the same as the in-depth way from that guide. The only difference I see is how to check for readiness of components.

I'm using `rollout status` since it is precise to exactly when the components are ready indeed, instead of running `get all` (probably multiple times).

See also: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progressing-deployment

2020-11-03 17:28 UTC, ArthurSens commented
I've changed the pub-date to november 5th, so we can have extra time to do more changes in case we need :)

2020-11-18 17:22 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +pub-date: October 21
Adjust to Nov 18.  File name should be updated also.

2020-11-18 17:22 UTC, mazzystr requested changes
@ArthurSens Please resolve these couple issues then we should be ready to merge

2020-11-19 15:59 UTC, ArthurSens commented
Publication date adjusted for today(November 19th)

2020-12-07 19:19 UTC, mazzystr commented
@ArthurSens 
* Three small issues need to be resolved in content
* Yaspeller complaining in CI ([builds/744691465](https://travis-ci.org/github/kubevirt/kubevirt.github.io/builds/744691465))
```
$ yaspeller --only-errors ./**/*.md
Spelling check:
✗ /home/travis/build/kubevirt/kubevirt.github.io/_posts/2020-11-19-Monitoring-KubeVirt-VMs-from-the-inside.md 382 ms
-----
Typos: 7
1. arthursens (3:9, suggest: Arthur sens)
2. ServiceMonitors (38:280, count: 3, suggest: Service Monitors)
3. CustomResources (60:43, suggest: Custom Resources)
4. CDI’s (101:57, suggest: CGI's, CD-I's)
5. dataVolumeTemplate (181:84, count: 2)
6. PromQL (293:81, count: 2)
7. ServiceMonitor (count: 4, suggest: Service Monitor)

Capitalization: 1
1. prometheus (count: 2, suggest: Prometheus)
-----
```
* Update publication date.
* You'll probably need to rebase too.  I'm going to fix the links per the failing Netlify job in another PR.

2020-12-07 19:46 UTC, mazzystr commented
The qemu.org broken links were fixed on ...
`667327ea4c _posts/2018-05-08-KubeVirt-objects.markdown (Chris Callegari    2020-11-10 12:21:54 -0800 180)`

Please proceed with rebase.

2020-12-10 20:04 UTC, mazzystr commented on _posts/2020-10-21-Monitoring-KubeVirt-VMs-from-the-inside.md
> +pub-date: October 21
Moved publish date to Dec 10

2020-12-14 19:05 UTC, mazzystr commented
/lgtm
/approve

2020-12-14 19:12 UTC, merged