Create blog post for KubeVirt RunStrategies
kubevirt/kubevirt.github.io pull request #642
Opened 2020-10-23 19:07 UTC by stu-gott

Signed-off-by: Stu Gott <stu-gott@users.noreply.github.com>

**What this PR does / why we need it**:

Discusses the various RunStrategies available in KubeVirt

2020-10-26 15:10 UTC, stu-gott commented
@codificat it's not clear to me what went wrong with Travis. Can you advise?

2020-10-26 17:51 UTC, codificat commented
> @codificat it's not clear to me what went wrong with Travis. Can you advise?

It's the spell checker that is complaining because it doesn't understand [a few words](https://travis-ci.org/github/kubevirt/kubevirt.github.io/builds/738403446#L381-L391).

Some ot them you will have to add them to the dictionary in the `.yaspeller.json` file in the TLD (e.g. _RunStrategies_, the acronyms, your name). There is at least one legitimate typo (_accommodate_), and for a few of them you might consider actually changing the word, or add to the dictionary. I'm thinking in e,g, _October_ vs _Oct_  or _re-spawn_ vs _respawn_ .... up to you.

2020-10-28 18:02 UTC, codificat commented
The current check failure is unrelated to this PR, it's a couple of broken links in an older blog post... once #646 merges, a rebase should let this pass.

2020-10-29 12:36 UTC, stu-gott commented
Sounds good. I estimated a release date of tomorrow for this blog post to go live. Should I update the post date to be sometime next week then?

2020-10-29 12:37 UTC, stu-gott commented
/cc @rmohr @davidvossel 

Would one of you mind reviewing this from a technical content perspective?

2020-11-02 13:53 UTC, codificat commented
> Sounds good. I estimated a release date of tomorrow for this blog post to go live. Should I update the post date to be sometime next week then?

Well, we are already in _next week_, so that might be a sensible thing to do. If you update the post date, keep in mind that you should also rename the file to match it.

About the content: I'll let more knowledgeable engineers provide their review, but from my side I'll mention that I believe if would be nice to add a few relevant links within the text where appropriate - not as separate references, but in mentions. For example: link to the API spec when you mention it, the documentation about the new `RunStrategy` field...

By the way, a quick note on formatting: we usually use `code` format for references like `RunStrategy` or even `Running` (when it's a value in the spec/status), so I'd suggest to replace a few double quotes (") with backticks.

2020-11-18 17:26 UTC, mazzystr requested changes

2020-11-18 17:26 UTC, mazzystr commented on _posts/2020-10-30-run_strategies.md
> +[Machine Health Check](https://cnv3520--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/deploying-machine-health-checks.html#machine-health-checks-about_deploying-machine-health-ch
These Netlify links seem brittle.  Is there anyway to change to an official access.redhat.com link?

2020-12-02 20:26 UTC, stu-gott commented on _posts/2020-10-30-run_strategies.md
> +[Machine Health Check](https://cnv3520--ocpdocs.netlify.app/openshift-enterprise/latest/machine_management/deploying-machine-health-checks.html#machine-health-checks-about_deploying-machine-health-ch
Fixed

2020-12-02 20:28 UTC, stu-gott commented
@codificat Rebased and re-set the release date for Friday Dec 4. I think this post has had plenty of soak time at this point.

2020-12-03 13:23 UTC, codificat commented
There was a broken link, I added a commit to fix it.

Besides that, for some reason the link checker was reporting link failures to the katacoda scenarios - maybe this was a temporary glitch, let's see if that passes now.

Other than that,
/lgtm
/approve

2020-12-03 14:26 UTC, codificat commented
The link checker reports a failure again with the katacoda links (403, forbidden), but they do work. I'm wondering if it might be that katacoda doesn't like the user agent or something...

@mazzystr as you have been fighting with the link checker recently, does that ring a bell?

2020-12-03 19:03 UTC, stu-gott commented
@codificat this sounds like something unrelated to this PR directly and an issue with existing links elsewhere in the repository?

2020-12-04 11:53 UTC, codificat commented
> @codificat this sounds like something unrelated to this PR directly and an issue with existing links elsewhere in the repository?

Well, it's worse than that: tests are currently failing due to non-existing issues :confused: 

I'll merge this manually.

2020-12-04 11:54 UTC, merged