Fix broken links
kubevirt/kubevirt.github.io pull request #653
Opened 2020-11-10 17:12 UTC by mazzystr

**What this PR does / why we need it**:
Fix broken links

Fixes #issues/651

2020-11-10 17:28 UTC, codificat requested changes

2020-11-10 17:28 UTC, codificat commented on _posts/2018-05-08-KubeVirt-objects.markdown
> -Configures the [virtualize hardware](https://kubevirt.io/user-guide/#/creation/devices?id=clock) clock provided by [QEMU](https://www.qemu.org/docs/master/qemu-doc.html#Debug_002fExpert-options).
There is another instance of this same link on line 180 that also has to be fixed

2020-11-10 17:59 UTC, codificat commented
Assuming tests will pass this time,
/lgtm
/approve

2020-11-10 20:21 UTC, merged

2020-11-12 10:32 UTC, dankenigsberg commented on pages/quickstart_cloud.md
> +
@mazzystr the down side of this part is that we now send the readers to many providers who does not support virtualization. I think we should be more opinionated.