Update broken link to Fedora-Cloud qcow2 img.  Remove version where p…
kubevirt/kubevirt.github.io pull request #663
Opened 2020-12-09 18:18 UTC by mazzystr

**What this PR does / why we need it**:
Update broken link to Fedora-Cloud qcow2 img.  Remove version where possible

2020-12-09 18:52 UTC, codificat requested changes

2020-12-09 18:52 UTC, codificat commented on _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
> +If you try these examples yourself, you’ll need to download the **Fedora-Cloud-Base-33-1.2.x86_64.qcow2** image file in your working directory.
This change only delays another breakage once Fedora 33 is EOL.

Instead, I would suggest to leave everything as it is and just update this sentence to explain that "you will need to download a current version of the Fedora Cloud qcow2 image" (maybe include the link) and add that "this blog post was developed using Fedora 31 cloud images"

The link to the image itself was changed to a generic version-independent link in db7d9d6 (that link could be used here too)

2020-12-09 19:16 UTC, mazzystr commented on _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
> +If you try these examples yourself, you’ll need to download the **Fedora-Cloud-Base-33-1.2.x86_64.qcow2** image file in your working directory.
Fixed

2020-12-10 11:19 UTC, codificat commented
/lgtm
/approve

2020-12-10 23:44 UTC, mazzystr commented
@codificat darn link checker and redirect got me.  Fedora releases link fixed.  Please restamp lgtm/approve.

2020-12-11 15:34 UTC, codificat commented on _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
> +Below are a few options for importing. For each example, I’m using the Fedora Cloud x86_64 qcow2 image that can be downloaded [here](https://archives.fedoraproject.org/pub/fedora/linux/releases/)
Why point to the archives?

The update in this PR, as I understand it, attempts to make the post generic enough to cover current releases (the change below explicitly mentions that)... and for current releases, I believe the link should stay at `download.fedoraproject.org`, no? it's the URL that is used in https://alt.fedoraproject.org/cloud/

2020-12-14 19:17 UTC, mazzystr commented on _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
> +Below are a few options for importing. For each example, I’m using the Fedora Cloud x86_64 qcow2 image that can be downloaded [here](https://archives.fedoraproject.org/pub/fedora/linux/releases/)
Correct.  I'm trying to get this blog post generic enough so it self maintains without creating confusion from setting a static Fedora Cloud img version.

re link.... alternative has a redirect to the geographically closest mirror vs archive which is Fedora project hosted.  To me the only difference is who is serving the bits.  I don't see `https://alt.fedoraproject.org/cloud/` mentioned anywhere.   The urls are hidden behind the text.  We change to linking to the official Fedora project hosting site to avoid fighting with our own tools.  I thinks this is A-OK.

2020-12-14 19:19 UTC, mazzystr commented on _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
> +Below are a few options for importing. For each example, I’m using the Fedora Cloud x86_64 qcow2 image that can be downloaded [here](https://archives.fedoraproject.org/pub/fedora/linux/releases/)
Actually I see what you mean now.  https://alt.fedoraproject.org/cloud/ is the `latest` we were talking about.  I'll change the link to that.  :)

2020-12-15 17:24 UTC, codificat commented
/lgtm
/approve

2020-12-15 17:26 UTC, merged