refactor README.md
kubevirt/kubevirt.github.io pull request #714
Opened 2021-03-25 13:31 UTC by eifrach

Signed-off-by: Eran Ifrach <eifrach@redhat.com+>

**What this PR does**:
*  refactoring the README.md file.
* fix `make run` on Makefile

fixes #713

2021-03-25 13:34 UTC, eifrach commented
/assgin @mazzystr

2021-03-25 18:20 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -d --name website -p 4000:4000 -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount type=
Oh yea!  Thanks for fixing that.  The history was we were going to have user-guide and website cross check each other.  We needed the containers to run `--net=host` to make that happen.

2021-03-25 19:11 UTC, mazzystr requested changes

2021-03-25 19:11 UTC, mazzystr commented on README.md
> +
I'm not fond of the `Join our community` section being right here.  I don't think the website repo is the entry point into the project.

Can you change to the user-guide `Getting help` and `Developer`?  Let's see how it looks.

2021-03-29 15:42 UTC, mazzystr commented
/ok-to-test

2021-03-30 09:58 UTC, eifrach commented
@mazzystr  the link test is failing due to in issue in okd.io site. 
the link goes to version 1.5 that is not available anymore

2021-03-31 11:06 UTC, eifrach commented
/retest

2021-03-31 15:45 UTC, mazzystr commented
/approve
/lgtm

2021-03-31 15:50 UTC, merged