adding linter checks to Makefile
kubevirt/kubevirt.github.io pull request #719
Opened 2021-03-30 13:44 UTC by eifrach

Signed-off-by: Eran Ifrach <eifrach@redhat.com+>

**What this PR does :
* adding linter check to Makefile
* add linter config file

> Fixes #652

2021-03-30 15:36 UTC, mazzystr commented on Makefile
> +linter: | envvar
Would you be against calling the target `make check_lint`?  I want to be very clear and simple with what we are doing here.  Historically it's been a big hunt trying to figure out where and why CI failed.

The idea is to have three jobs run when a pull req is created....
* make check_lint
* make check_spelling
* make check_links

2021-03-30 15:36 UTC, mazzystr commented on Makefile
> +	rm -rf markdownlint-cli
A contributor just wants to run lint... not have to wait 5-10 mins to build a img.  Let's keep this target minimal.

Take a look at issues/715 where we want to consolidate all the img building into a single target so that Prow can build and push to Docker Hub.  This would be a good start for that effort.

2021-03-30 15:36 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -ti --rm --name markdownlint-cli -v ${PWD}:/srv:ro  --workdir /srv  ${TAG} --config /srv/.markdownlint.jsonc **/*.md
Very close.  :)

* `--name` will probably change if we implement issues/715
* `-ti`, I think `-d` daemon mode is a better option.  I'm happy to debate it :)
* SELinux option missing for volume mount
* Hidden files are a pain to understand and modify based on dealing with the yaspeller dictionary file.  Let's have this be a normal file in the git repo then do a volume mount.  See [Makefile](https://github.com/kubevirt/kubevirt.github.io/blob/source/Makefile) L127 and L139.
* Use a regex tester to make sure that `**/*.md` captures the entire dir hierarchy.  I've seen some really bad behavior with a similar regex

2021-03-30 16:35 UTC, mazzystr requested changes
See comments

2021-03-31 18:44 UTC, mazzystr commented
/ok-to-test

2021-03-31 18:54 UTC, mazzystr commented
And another 302 link failure...
```
6:46:33 AM: - ./_site/2018/Deploying-KubeVirt-on-a-Single-oVirt-VM.html
6:46:33 AM:   *  External link https://docs.okd.io/1.5/install_config/install/host_preparation.html#configuring-docker-storage failed: 301 Number of redirects hit maximum amount
```

2021-04-13 07:10 UTC, eifrach commented
closing this PR  -- 
the fix it added in 
PR #725

2021-04-13 07:10 UTC, closed without merging