Update lab2 for latest minikube
kubevirt/kubevirt.github.io pull request #723
Opened 2021-04-07 20:52 UTC by cwilkers

- Remove storage-setup.yml and its references
  - Alter pvc_fedora.yml to remove storageclass
  - Download pvc_fedora.yml locally to use it later
  - Add commands to delete and recreate pvc if needed
  - Alter instructions to excise mention of hostpath-provisioner
  - Updated to use minikube ip instead of status

Fixes #695

2021-04-07 21:53 UTC, cwilkers commented
re-pushed to get around spell check not liking "Minikube's"

2021-04-07 23:15 UTC, mazzystr commented
@cwilkers You're gonna have to add a commit to fix the following links...
```
- ./_site/2019/prow-jobs-for-kubevirt.html

  *  External link https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml failed: 404 No error

- ./_site/summit/index.html

  *  External link https://github.com/nunnatsa%E2%80%8B failed: 404 No error
  ```

2021-04-07 23:56 UTC, mazzystr requested changes

2021-04-07 23:56 UTC, mazzystr commented on _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
> +kubectl create -f pvc_fedora.yml
I've never like the idea of making users pulling in yml's

I think we would be better off doing something like ...
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
EOF
```
That yaml is still doing hostpath.  Is that correct?

2021-04-07 23:56 UTC, mazzystr commented on _includes/scriptlets/lab2/16_minikube_vm_ip.sh
> -  kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.74
I think we should keep the minikube status to make sure all the pieces of minikube are running

2021-04-07 23:56 UTC, mazzystr commented on labs/kubernetes/lab2.md
There's an English mistake in L15.  

`[CDI](https://github.com/kubevirt/containerized-data-importer) is an utility designed to import Virtual Machine images for use with Kubevirt.`

Would you mind changing that to `is a utility`

2021-04-07 23:56 UTC, mazzystr commented on _includes/scriptlets/lab2/00_delete_and_recreate_pvc.sh
> +kubectl delete -f pvc_fedora.yml --wait
Do we really need this for fresh installs?

2021-04-07 23:56 UTC, mazzystr commented on labs/kubernetes/lab2.md
> +Check the status of the cdi CustomResource (CR) created in the previous step. The CR's Phase will change from Deploying to Deployed as the pods it deploys are created and reach the Running state.
CDI is a _CustomResourceDefinition_ (CRD)

2021-04-07 23:56 UTC, mazzystr commented on labs/kubernetes/lab2.md
> +#### Use CDI to Import a Cloud Image
sed s/Cloud/Disk/

2021-04-07 23:56 UTC, mazzystr commented on labs/kubernetes/lab2.md
> +```bash
You should be able to do a code block within the annotation.  Hack on it and let's see how it looks.

2021-04-08 14:07 UTC, cwilkers commented on _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
> +kubectl create -f pvc_fedora.yml
I dropped the storageClassName from the version in the PR.

2021-04-08 14:08 UTC, cwilkers commented on _includes/scriptlets/lab2/16_minikube_vm_ip.sh
> -  kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.74
Minikube setup is out of scope for this particular lab, there's a separate lab just for that, I thought. The minikube status no longer returns the IP, which is what we're after here.

2021-04-08 14:10 UTC, cwilkers commented on labs/kubernetes/lab2.md
Sure, (but...) I didn't want to make the PR huge by taking on the job of updating AND editing.

2021-04-08 14:11 UTC, cwilkers commented on _includes/scriptlets/lab2/00_delete_and_recreate_pvc.sh
> +kubectl delete -f pvc_fedora.yml --wait
No, that's part of the Note block for if there's an issue with the link given to CDI (and with the current mirror problem outlined in https://github.com/kubevirt/containerized-data-importer/issues/1737 there is need for knowing this work-around)

2021-04-08 22:23 UTC, mazzystr commented on _includes/scriptlets/lab2/16_minikube_vm_ip.sh
> -  kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.74
You're right.  Excellent point.

2021-04-08 22:27 UTC, mazzystr commented on labs/kubernetes/lab2.md
s'ok.  we're editing the next line so might as well pick up a little trash on the way.

2021-04-08 22:43 UTC, mazzystr commented
Very good!  Looking better yet!
/approve
/lgtm

2021-04-08 22:44 UTC, merged