new container for local testing
kubevirt/kubevirt.github.io pull request #725
Opened 2021-04-12 14:31 UTC by eifrach

**What this PR does / why we need it**:

* changing make file to use a single container for all local test
* adding linter checks 

> Fixes #715 #652

2021-04-12 14:32 UTC, eifrach commented
/hold
/assign @mmazur

2021-04-13 21:57 UTC, mazzystr requested changes

2021-04-13 21:57 UTC, mazzystr commented on .yaspeller.json
>    "dictionary": [
Let's remove and put this in a different pull req

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> -	@echo -n
If you can change the commit so these diffs go away it will make the pull req smaller

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	OUTPUT=`${CONTAINER_ENGINE} run -it --rm --name website --net=host -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site -
`--trace` the output of this command.  It's very important that `rake links:userguide_selectors` outputs a csv so that casperjs can process the data correctly

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> -	if [ "$${RETVAL}" ]; then exit 1; else echo "Complete!"; fi
I highly recommend we work to remove most of this diff to make the pull req smaller.

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${DEBUG}$(eval export TAG='localhost/kubevirt.io')
wrong tag

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${DEBUG} curl https://raw.githubusercontent.com/kubevirt/project-infra/master/images/kubevirt-kubevirt.github.io/update-yaspeller.sh -o update-yaspeller.sh; \
file doesn't exist

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	bash update-yaspeller.sh
file doesn't exist

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -it --rm --name yaspeller -v ${PWD}:/srv:ro${SELINUX_ENABLED} -v /dev/null:/srv/Gemfile.lock ${TAG} /bin/bash -c 'yaspeller -c /srv/.yaspeller.json --only-errors --ignore-tag
good thing we still have a local .yaspeller dictionary file otherwise the mount would break

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -d --name website --net=host -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount type=tm
Something has changed here.  Jekyll now listens on 127.0.0.1:4000. 

This is the single most important command in the entire Makefile.  I cannot approve this pull req until this is fixed.

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${DEBUG}if [[ `${CONTAINER_ENGINE} image ls | grep localhost/kubevirt.io` ]]; \
wrong tag

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${DEBUG}$(eval export TAG='localhost/kubevirt.io')
wrong tag

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${DEBUG}$(eval export TAG='jekyll/jekyll')
Also there are way too many `${DEBUG}$(eval export TAG=`'s sprinkled throughout.  They can be consolidated to the `envval` target

2021-04-13 21:57 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -it --rm --name website --net=host -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount t
why the trailing comment?

2021-04-13 21:58 UTC, mazzystr requested changes

2021-04-13 21:58 UTC, mazzystr commented on .gitignore
> +update-yaspeller.sh
Let's not add this

2021-04-13 22:10 UTC, mazzystr commented
@eifrach This is an XL pull req that at the heart is fatally broken.  Jekyll runtime has changed and the app is no longer accessible.  

I really think we're trying to take on too much here.  Near as I can tell we have 3 items going on ... Add linting, consolidate build, update dictionary.

I highly suggest these items be broken out into smaller pull reqs.

2021-04-16 20:19 UTC, mazzystr commented
/retest all

2021-04-16 20:19 UTC, mazzystr commented
/test all

2021-04-18 09:35 UTC, eifrach commented on Makefile
> +	${DEBUG}git clone https://github.com/kubevirt/project-infra.git /tmp/project-infra; \
@mazzystr This Dockerfile needs all the files in the directory.
what you are suggesting we do
take a look the the repo folder
https://github.com/eifrach/project-infra/tree/kubevirt.io/images/kubevirt-kubevirt.github.io

2021-04-18 17:03 UTC, mazzystr commented
***@***.*** can you add that Dockerfile to the pull req to project-infra? I
didn't have a copy so wasn't able to do it on Fri*

On Sun, Apr 18, 2021, 2:35 AM Eran Ifrach ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Makefile
> <https://github.com/kubevirt/kubevirt.github.io/pull/725#discussion_r615371218>
> :
>
> >  	@echo
> -	@echo "${GREEN}Makefile: Check links and selectors to userguide on website content${RESET}"
> +
> +
> +## Stop site
> +stop: | envvar
> +	@echo "${GREEN}Makefile: Stop site${RESET}"
> +	${CONTAINER_ENGINE} rm -f website 2> /dev/null; echo
> +	@echo -n
> +
> +## Build image localhost/kubevirt.io
> +build_image: | envvar
> +	${DEBUG}$(eval export TAG='localhost/kubevirt.io')
> +	@echo "${GREEN}Makefile: Cloneing Repo ${RESET}"
> +	${DEBUG}git clone https://github.com/kubevirt/project-infra.git /tmp/project-infra; \
>
> @mazzystr <https://github.com/mazzystr> This Dockerfile needs all the
> files in the directory.
> what you are suggesting we do
> take a look the the repo folder
>
> https://github.com/eifrach/project-infra/tree/kubevirt.io/images/kubevirt-kubevirt.github.io
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubevirt/kubevirt.github.io/pull/725#discussion_r615371218>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS5KZ4NS4JRKAOOZQAWA4DTJKRW3ANCNFSM42ZNILQQ>
> .
>

2021-04-26 12:48 UTC, eifrach reviewed
/retest

2021-04-26 20:55 UTC, mazzystr requested changes

2021-04-26 20:55 UTC, mazzystr commented on Makefile
> +	@$(eval export DEBUG=@)~
This typo breaks the Makefile entirely

```
$ make run
/bin/sh: /home/ccallegar: Is a directory
make: *** [Makefile:43: envvar] Error 126
```

2021-04-26 20:55 UTC, mazzystr commented on Makefile
>  check_spelling: | envvar stop
We're dead in the water again

```
$ make check_spelling

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Check spelling on site content
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     66      0 --:--:-- --:--:-- --:--:--    66
bash: line 1: 404:: command not found
make: *** [Makefile:161: check_spelling] Error 127
```

This is why we need to have the curl conditional in place.  This is a guessing game until update-yaspeller.sh is merged into project-infra.

Did you test with SELinux enabled?

2021-04-26 20:55 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -d --name website --net=host -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount type=tm
And broke again...

```
$ make run

Makefile: Stop site
podman rm -f website 2> /dev/null; echo

Makefile: Run site
for i in .jekyll-cache _site Gemfile.lock; do rm -rf ./"${i}" 2> /dev/null; echo -n; done
podman run -d --name website --net=host -v /home/ccallegar/git/kubevirt/website:/srv/jekyll:ro -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount type=tmpfs,destination=/srv/jekyll/.jekyll-cache --workdir=/srv/jekyll localhost/kubevirt-kubevirt.github.io /bin/bash -c "jekyll serve --trace --force_polling --future"
f01590b5a4f0165adea7707c98cb7cf7659a01d59b1c88c922bf091eb1b2e868


$ podman logs -f website
....
blah blah blah
.....

                    done in 5.542 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

NOTICE the app is now listening to 127.0.0.1.  This is wrong.  The app should be listening to 0.0.0.0.  

App behavior has changed somehow.  Maybe we installed a newer version in `make build_img`?  Maybe the app config file has changed?

2021-04-26 20:55 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -it --rm --name yaspeller -v ${PWD}:/srv:ro${SELINUX_ENABLED} -v /dev/null:/srv/Gemfile.lock --workdir=/srv ${IMGTAG} /bin/bash -c 'yaspeller -c /srv/.yaspeller.json --only-e
This cmd now fails to skip items in `excludeFiles` key in `yaspeller.json` file
```
$ make check_spelling | grep "✗"
✗ ./.git/logs/refs/remotes/eifrach/README.md 577 ms
✗ ./README.md 502 ms
✗ ./TODO.md 516 ms
✗ ./GUIDELINES.md 621 ms
✗ ./node_modules/@babel/helper-validator-identifier/README.md 461 ms
✗ ./node_modules/@types/color-name/README.md 455 ms
✗ ./node_modules/@types/parse-json/README.md 485 ms
.....
blah blah blah ./node_modules
.....
✗ ./pages/summit.md 1218 ms
make: *** [Makefile:161: check_spelling] Error 1
```

2021-04-26 20:55 UTC, mazzystr commented on Makefile
> +	${DEBUG} curl $${REPOPATH}/update-yaspeller.sh | bash -
If I replace L161 with original conditional script to retrieve yaspeller.json file I can proceed with peer review.

2021-04-27 10:32 UTC, eifrach commented on Makefile
>  check_spelling: | envvar stop
no this is failing because the sysinfra is not merged yet.
I've added a variable for testing
```bash
export REPOPATH=https://raw.githubusercontent.com/eifrach/project-infra/kubevirt.io/images/kubevirt-kubevirt.github.io
```

2021-04-27 10:39 UTC, eifrach commented on Makefile
> +	${CONTAINER_ENGINE} run -d --name website --net=host -v ${PWD}:/srv/jekyll:ro${SELINUX_ENABLED} -v /dev/null:/srv/jekyll/Gemfile.lock --mount type=tmpfs,destination=/srv/jekyll/_site --mount type=tm
fixed

2021-04-27 14:31 UTC, eifrach commented
Closing PR reopening in a new branch

2021-04-27 14:31 UTC, closed without merging