Add blog post Automatic Windows Installation With Tekton Pipelines
kubevirt/kubevirt.github.io pull request #727
Opened 2021-04-19 08:12 UTC by suomiy

This blog shows how KubeVirt Tekton Tasks can be utilized to automatically install and setup Windows VMs from scratch

2021-04-19 08:14 UTC, suomiy commented
Please review @mazzystr @dankenigsberg

2021-04-19 08:16 UTC, suomiy commented
this post is similar to and depends on https://github.com/kubevirt/kubevirt-tekton-tasks/pull/80

2021-04-19 08:52 UTC, dankenigsberg requested changes
better call in @eifrach to review this.

2021-04-19 08:52 UTC, dankenigsberg commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +It will then spin up a VM and use Windows Answer Files to automatically install the system.
I (think) you later refer to the term "installation VM", better define it here. Also, I find "system" as too vague.
```suggestion
It will then spin up an installation VM and use Windows Answer Files to automatically install the VM.
```

2021-04-19 08:52 UTC, dankenigsberg commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Then the pipeline will wait for the installation to complete and will delete the installation VM while keeping the artifact PVC with the installed system.
```suggestion
Then the pipeline will wait for the installation to complete and will delete the installation VM while keeping the artifact PVC with the installed operating system.
You can use the artifact PVC for ???
```

2021-04-19 08:52 UTC, dankenigsberg commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +You can then create a VM with this DataVolume (`xxxxx` needs to be replaced in the following yaml) to test it.
I think you should suggest to first clone the PVC. If you don't intend to create multiple VMs from the same PVC, you could have just kept using the installation VM.

2021-04-19 10:58 UTC, eifrach commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +    "Tekton Pipelines"
missing comma 
```markdown
 "Tekton Pipelines",
```

2021-04-19 10:58 UTC, eifrach commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +author: Filip Křepinský
the spelling checks are falling due to the name
can you add it on the upstream
https://github.com/kubevirt/project-infra/blob/master/images/yaspeller/.yaspeller.json

2021-04-19 12:51 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +It will then spin up a VM and use Windows Answer Files to automatically install the system.
Thanks, fixed

2021-04-19 12:52 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Then the pipeline will wait for the installation to complete and will delete the installation VM while keeping the artifact PVC with the installed system.
fixed and added a new sentence: `You can later use the artifact PVC as a base image and copy it for new VMs`

2021-04-19 12:53 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +You can then create a VM with this DataVolume (`xxxxx` needs to be replaced in the following yaml) to test it.
good idea, changed the description and added a dataVolumeTemplate to the VM

2021-04-19 12:53 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +    "Tekton Pipelines"
thanks

2021-04-19 12:54 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +author: Filip Křepinský
It might pass since I am already added to https://github.com/kubevirt/kubevirt.github.io/blob/source/.yaspeller.json

2021-04-19 13:52 UTC, eifrach commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +author: Filip Křepinský
it's going to change to the upstream, nvm i need to create some changes there i will add you
 mark as resolved

2021-04-19 14:04 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +author: Filip Křepinský
ok, thanks

2021-04-19 14:07 UTC, eifrach commented
lgtm

/assign @mazzystr

2021-04-19 20:37 UTC, mazzystr requested changes

2021-04-19 20:38 UTC, mazzystr commented
@suomiy Everything look real good!  Let's shrink that pic to a manageable size and then we can roll to prod.

2021-04-20 01:44 UTC, jwmoss commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +- [YAML files used in this example](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/examples/pipelines/windows-installer)
Hi! This appears to be a 404 not found.

2021-04-20 07:09 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +- [YAML files used in this example](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/examples/pipelines/windows-installer)
merged https://github.com/kubevirt/kubevirt-tekton-tasks/pull/80, so it should work now

2021-04-20 07:11 UTC, suomiy commented on _posts/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +![Started Windows VM](/assets/2021-04-19-Automatic-Windows-Installation-With-Tekton-Pipelines/win-started.png "Started Windows VM")
done and I doubled the thumbnail size to 200px - not sure what size is preferred?

2021-04-20 07:12 UTC, suomiy commented
@mazzystr everything should be in order now, I hope

2021-04-20 12:11 UTC, pcbailey reviewed
This looks great! I left some small typographical and grammatical suggestions.

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +   from the empty PVC and with `windows-10-source-*` PVC attached as a CD-ROM.
"and with `windows-10-source-*`" -> "and with the `windows-10-source-*`"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +4. ` wait-for-vmi-status` task waits until the VM shutdowns.
"shutdowns" -> "shuts down"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +To run the pipeline we need to create the following `PipelineRun` which references our `Pipeline`.
"run the pipeline we need" -> "run the pipeline, we need"

"following `PipelineRun` which" -> "following `PipelineRun`, which"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The timeout should be changed appropriately, for example if you have a slow download connection.
"changed appropriately, for example if you have a" -> "changed appropriately; for example, if you have a"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Once the pipeline run completes you should be left with `windows-10-base-xxxxx` PVC (backed by DataVolume).
"pipeline run completes you should" -> "pipeline run completes, you should"

"left with `windows-10-base-xxxxx` PVC" -> "left with a `windows-10-base-xxxxx` PVC"

"(backed by DataVolume)" -> "(backed by a DataVolume)"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +You can start the VM and login with `Administrator` : `changepassword` credentials. Then you should be welcomed to your fresh VM.
"welcomed to your" -> "welcomed by your"

2021-04-20 12:11 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Tekton Pipelines can be used to create a single `Pipeline` that encapsulates the installation process which can be run and replicated with `PipelineRuns`.
"installation process which" -> "installation process, which"

2021-04-20 15:21 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +This blog shows how we can easily automate a process of installing Windows VMs on KubeVirt with [Tekton Pipelines](https://github.com/tektoncd/pipeline).
@pcbailey a vs the ... a implies there are many ways.  the implies this is the only way.  I agree _the_ sounds like more correct English but do we want to imply this pipeline is the only way?

2021-04-20 15:21 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The pipeline will be built with [KubeVirt Tekton Tasks](https://github.com/kubevirt/kubevirt-tekton-tasks) which include all the necessary tasks for this example.
@suomiy seconded

2021-04-20 15:24 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The pipeline will prepare an empty PVC (Persistent Volume Claim) and download a Windows source ISO into another PVC. Both of them will be initialized with CDI (Containerized Data Importer).
@suomiy seconded.  This is consistent with the rest of user-guide.

2021-04-20 15:27 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +In our case it is an `Administrator` user with `changepassword` password.
@pcbailey 98% of comma uses require there to be a complete sentence before and after a comma unless it's a list.  `In our case` is not a complete sentence.  My old stodgy English prof would have pushed up her glasses and clicked her red pen.  

My vote is no comma

2021-04-20 15:27 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +2. `create-base-dv` task creates empty PVC for new windows installation called `windows-10-base-*`.
@suomiy seconded

2021-04-20 15:28 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +   from the empty PVC and with `windows-10-source-*` PVC attached as a CD-ROM.
@suomiy seconded

2021-04-20 15:28 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +4. ` wait-for-vmi-status` task waits until the VM shutdowns.
@suomiy seconded

2021-04-20 15:29 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +To run the pipeline we need to create the following `PipelineRun` which references our `Pipeline`.
@pcbailey my vote is no comma

2021-04-20 15:44 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The timeout should be changed appropriately, for example if you have a slow download connection.
Comma after semicolon....ug!  ;)

semicolon yes.  comma...`for example` becomes a comma splice so my vote is no

2021-04-20 17:18 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Once the pipeline run completes you should be left with `windows-10-base-xxxxx` PVC (backed by DataVolume).
seconded

2021-04-20 17:18 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +You can start the VM and login with `Administrator` : `changepassword` credentials. Then you should be welcomed to your fresh VM.
seconded

2021-04-20 17:18 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Tekton Pipelines can be used to create a single `Pipeline` that encapsulates the installation process which can be run and replicated with `PipelineRuns`.
-1.  Comma splice

2021-04-20 17:19 UTC, mazzystr requested changes
@suomiy A few more English nitpicks...

2021-04-21 11:14 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +This blog shows how we can easily automate a process of installing Windows VMs on KubeVirt with [Tekton Pipelines](https://github.com/tektoncd/pipeline).
@mazzystr I don't know that the average reader would read that much into it; but, if you're concerned, leave it as it is. It just doesn't sound correct.

2021-04-21 11:15 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +To run the pipeline we need to create the following `PipelineRun` which references our `Pipeline`.
@mazzystr I waffled back and forth on this one, so I will gladly bow to your suggestion.

2021-04-21 11:27 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The timeout should be changed appropriately, for example if you have a slow download connection.
@mazzystr See rule 2 here: https://www.grammarbook.com/punctuation/semicolons.asp. There's also the option of simply splitting the sentences.

2021-04-21 11:32 UTC, pcbailey commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +Tekton Pipelines can be used to create a single `Pipeline` that encapsulates the installation process which can be run and replicated with `PipelineRuns`.
You are correct. Objection sustained.

I enjoyed this! Let's do it again sometime. =)

2021-04-21 18:28 UTC, suomiy commented
@pcbailey @mazzystr Thanks a lot for your review. I tried to follow your remarks, so hopefully I got it right :)

2021-04-21 18:31 UTC, suomiy commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +2. `create-base-dv` task creates empty PVC for new windows installation called `windows-10-base-*`.
@pcbailey @mazzystr I am wondering if we should also write an article here `a new windows installation`

2021-04-21 19:45 UTC, mazzystr commented on _posts/2021-04-20-Automatic-Windows-Installation-With-Tekton-Pipelines.md
> +The timeout should be changed appropriately, for example if you have a slow download connection.
Yup!  When in doubt just split the sentence to avoid the run-on

2021-04-21 19:46 UTC, mazzystr commented
Let's roll!

/lgtm
/approve

2021-04-21 19:47 UTC, merged

2021-04-22 09:26 UTC, suomiy commented
Great!