Issue#711
kubevirt/kubevirt.github.io pull request #728
Opened 2021-04-20 20:25 UTC by xphyr

This PR is in response to Issue #711 The blog post details how to use the new Intel vGPU detection added in kubevirt  release v0.40.0. The idea is to show how to try this feature out on a single machine leveraging Centos 8.3 and minikube. It is a semi-complex topic because it really combines multiple existing blog posts such as:
* installing kubevirt
* installing CDI
* building Windows virtual machine

I have tried to pull all this together in one post. Please let me know what thoughts and feedback you have on this, and thanks for your consideration.

2021-04-20 20:45 UTC, mazzystr commented
/ok-to-test

2021-04-21 19:16 UTC, xphyr commented
I picked an arbitrary date for the publication out a week.... let me know if I need to change anything there as I wasnt sure when it might get published.

2021-04-21 19:50 UTC, mazzystr commented
@xphyr  Publishing date is arbitrary.  It's up to you.

2021-04-21 21:44 UTC, mazzystr requested changes

2021-04-21 21:44 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +We can now start the virtual machine with `virtctl start win10vm1`. Check to ensure that the VM is running with `kubectl get vm`.
Can we reference another `Install windows on a vm within KubeVirt` blog or user-guide doc?

It will save 150 lines in this post if we do.

2021-04-21 21:44 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ ssh -L 12345:localhost:12345 <username>@<kubevirt host name ror IP>
I think we can do better than ssh port fwding.

How about a minikube service or tunnel?

2021-04-22 13:23 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +  * kubectl - See [Install and Set Up kubectl on Linux](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)
The minikube quickstart doesn't actually say where to get minikube from.  This was why I linked to the official minikube start docs, as it has links/install instructions for Linux, Windows and Mac. I can change it if you think that best.

2021-04-22 13:46 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
@mazzystr I tried to use the minikube addons to enable kubevirt, however it does not appear to be working.
```
[markd@kubevirt ~]$ minikube addons enable kubevirt
    ▪ Using image bitnami/kubectl:1.17
🌟  The 'kubevirt' addon is enabled
[markd@kubevirt ~]$ kubectl get ns; kubectl get all -n kubevirt
NAME              STATUS   AGE
default           Active   3m1s
kube-node-lease   Active   3m2s
kube-public       Active   3m2s
kube-system       Active   3m2s
No resources found in kubevirt namespace.
```

If we can figure out why the minikube addons is not working, we could patch the kubevirt-cr to add the Intel detection.

Thoughts?

2021-04-22 17:15 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
some additional information on this, if I switch the minikube install to use "driver=none" and switch to using docker-ce insteadd of podman, the `minikube addons enable kubevirt` command works just fine.

2021-04-22 17:55 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
I wanted to use podman, however when using the podman driver you are not able to get to the CDI-uploadproxy directly resulting in the need for additional ingress configuration. In addition, this allows you to get larger space for holding persistent volumes. I am open to other suggestions on this if there is a better way to do it.

2021-04-22 21:06 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +  * kubectl - See [Install and Set Up kubectl on Linux](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)
That is true.  agreed

2021-04-22 21:17 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
Interesting.  Are you using latest patches and latest minikube version?

2021-04-22 21:20 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +tags: vgpu, gpu
This should be resolved with the latest push.

2021-04-22 21:21 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +Starting with 5th generation Intel Core processors that have Intel Graphics Processors it is possible to share the graphics processor between multiple virtual machines. In Linux, this sharing of a GP
This should be resolved with the latest push.

2021-04-22 21:21 UTC, mazzystr requested changes

2021-04-22 21:21 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
I use the following prereq for Fedora + minikube....
```
* Fedora 32 uses cgroups v2.  Since k8s doesn't support v2 at this time the kernel must be directed to use v1.  Execute this command to trigger that function then reboot ...
  sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

* Firewalld must be running.  If it's not running CNI will not create nat or filter rules
  firewall-cmd --add-port=30000-65535/tcp --permanent
  firewall-cmd --add-port=30000-65535/udp --permanent
  firewall-cmd --add-port=10250-10252/tcp --permanent
  firewall-cmd --add-port=10248/tcp --permanent
  firewall-cmd --add-port=2379-2380/tcp --permanent
  firewall-cmd --add-port=6443/tcp --permanent
  firewall-cmd --add-port=8443/tcp --permanent
  firewall-cmd --add-port=9153/tcp --permanent
  firewall-cmd --add-service=dns --permanent
  firewall-cmd --add-interface=cni-podman0 --permanent
** DO NOT ... firewall-cmd --reload ... after minikube is running!!!

* Install rpms
  yum install -y gdm libvirt virt-manager podman podman-docker

* Install CRI-O
  cri-o install and quickstart is [here](https://cri-o.io/)

  dnf module list cri-o
  VERSION=1.18
  dnf module enable cri-o:$VERSION
  dnf install cri-o
  yum install -i cri-tools
  systemctl enable --now crio
```

minikube start cmd is 
```
minikube start --driver=none --container-runtime=crio
```

SELinux disabled is also a NO-NO

2021-04-22 21:24 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
I am using the minikube downloaded from the minikube site:

```
$ minikube version
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
```

This was obtained following the instructions here: https://minikube.sigs.k8s.io/docs/start/ 

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
```

2021-04-22 21:28 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
OK, let me install Fedora 32 on my box instead of Centos and re-write based on your instructions above and see where I get.

2021-04-22 23:15 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
@mazzystr I followed all your steps above and we are getting closer.  Are you running your `minikube start` command with "sudo" or directly as root? That is the only way I am able to get it to run is with sudo. Also the only way I could get minikube to install on Fedora32 was to do a `setenforce=0` otherwise kubelet would not start.

also ... interestingly `minikube addons enable kubevirt` does not work in this configuration.  Reviewing the logs in the kubevirt-install-manager pod it just says:

```
error: the path "/manifests/kubevirt-base.yaml" does not exist
error: the path "/manifests/kubevirt.yaml" does not exist
```

2021-04-22 23:23 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
I figured out why the kubevirt addon is not working. dns resolution is not working inside the minikube cluster so the install script is failing.

2021-04-22 23:46 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
disabling firewalld gets outbound access working again (which also makes `minikube addons enable kubevirt work`) ... after more digging, you also need `firewall-cmd --add-masquerade --permanent` or else things in the cluster cant talk out to the outside world ...

2021-04-23 17:48 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ ssh -L 12345:localhost:12345 <username>@<kubevirt host name ror IP>
Since I moved this over to Fedora Workstation and all of this is occuring on one machine, I was able to remove all of this ssh port forwarding. You can mark this one resolved.

2021-04-23 17:57 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +We can now start the virtual machine with `virtctl start win10vm1`. Check to ensure that the VM is running with `kubectl get vm`.
we need to have the GPU portion in the yaml for this to work. What I could do is put the yaml as an file in the attachment directory so its not quite so long. Let me know if this would be OK.

2021-04-23 18:00 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +We can now start the virtual machine with `virtctl start win10vm1`. Check to ensure that the VM is running with `kubectl get vm`.
Let's try it and see how it looks in Netlify.  I don't want to lose readers in monolithic walls of text.

2021-04-23 18:02 UTC, xphyr commented
I have migrated the setup/demo over to a Fedora 32 setup. I am also using the process you suggested for deploying minikube. I am re-running the entire set of steps from the top to ensure that they work properly and I captured all the changes. This should be more straight forward for someone to follow.

2021-04-23 18:04 UTC, mazzystr requested changes

2021-04-23 18:04 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +😄  minikube v1.19.0 on Fedora 22
Fedora 22?  This is strange :/

2021-04-23 18:05 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +😄  minikube v1.19.0 on Fedora 22
yep, you are right ... its a typo that I have already fixed in my local copy.

2021-04-23 18:16 UTC, mazzystr requested changes

2021-04-23 18:16 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +EOM
Shadowman says be consistent.  Let's pick EOM or EOF and ensure a space between the `<<` and `E...` throughout the document.

2021-04-23 18:22 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +EOM
More consistency.  Either PS1s get added to all cmds or they get removed completely.

My preference is no PS1s so that the copy function will copy all the commands and they can be pasted into cmd terminal and run correctly.

2021-04-23 18:26 UTC, mazzystr requested changes

2021-04-23 18:26 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +cat > kubevirt-patch.yaml <<EOF
See previous consistency comment

2021-04-23 18:26 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ cat > cdi-nodeport.yaml << EOF
See previous consistency comment

2021-04-23 18:26 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +<div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
You caught my breath with this picture!  This is amazing!

Would it be possible to add a picture at the very beginning with screenshot of the before FPS?

2021-04-23 21:58 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +😄  minikube v1.19.0 on Fedora 22
this is now resolved

2021-04-23 21:58 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +EOM
Thanks for catching this. all instances are EOF and spacing was also fixed.

2021-04-23 21:59 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +cat > kubevirt-patch.yaml <<EOF
Fixed

2021-04-23 22:00 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +<div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
Done, I also updated the intro to give a reason for the slow screenshot please review and let me know your thoughts.

2021-04-23 22:01 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +$ export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
All of this has been resolved, and is properly documented in a repeatable manner in Fedora 32.

2021-04-23 22:02 UTC, xphyr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
Thanks for the guidance here. Please see my comments above, as well as the steps that I documented in the blog post. Note that SELINUX disable is required to run with driver=none per the minikube documentation.

2021-04-26 18:08 UTC, mazzystr commented on _posts/2021-04-30-intel-vgpu-kubevirt.md
> +In order to use minikube on Centos 8.3 we will be installing the Docker binaries as these allow you to do a "bare metal" install of Kubernetes onto your Centos box. Use the following commands to upda
I bounce between running `driver=none` as root and running `driver=podman` and non-root depending on the nature of my test.  

I'm +1 with running `driver=none` as root with SELinux disabled.  I'll take that battle over to kubernetes/minikube.

2021-04-26 19:29 UTC, merged