add new continer to Makefile
kubevirt/kubevirt.github.io pull request #731
Opened 2021-04-27 14:45 UTC by eifrach

Signed-off-by: Eran Ifrach <eifrach@redhat.com>

**What this PR does **:

* Modifying Make filewith a single container for all tests/runs
* Depends on [PR-1115](https://github.com/kubevirt/project-infra/pull/1155) on Sysinfra 

> Fixes #715

2021-04-27 14:46 UTC, eifrach commented
/assign @mazzystr

2021-04-27 21:00 UTC, mazzystr requested changes

2021-04-27 21:00 UTC, mazzystr commented on Makefile
> +	${DEBUG} curl $${REPOPATH}/update-yaspeller.sh | bash -  > /dev/null  2>&1 || echo "${YELLOW} Cannot get latest yaspeller, Working with local yaspeller ${RESET}"
How about we skip this part so we don't have to rely on the project-infra guys and their CI?

2021-04-27 22:24 UTC, mazzystr requested changes

2021-04-27 22:24 UTC, mazzystr requested changes

2021-04-27 22:24 UTC, mazzystr commented on Makefile
> +## Build image localhost/kubevirt.io
localhost/kubevirt-kubevirt.github.io

2021-04-27 22:28 UTC, mazzystr requested changes

2021-04-27 22:28 UTC, mazzystr commented on Makefile
> +	${CONTAINER_ENGINE} run -it --rm --name yaspeller -v ${PWD}:/srv:ro${SELINUX_ENABLED} -v /dev/null:/srv/Gemfile.lock --workdir=/ ${IMGTAG} /bin/bash -c 'yaspeller -c /srv/.yaspeller.json --only-erro
change `--name yaspeller` to `--name website`

2021-04-27 22:32 UTC, mazzystr commented
/ok-to-test

2021-04-27 22:39 UTC, mazzystr commented on Makefile
> +	@echo "${GREEN}Makefile: Check Container status${RESET}"
`Container` should be `container`

2021-04-28 07:20 UTC, eifrach commented on Makefile
> +	${DEBUG} curl $${REPOPATH}/update-yaspeller.sh | bash -  > /dev/null  2>&1 || echo "${YELLOW} Cannot get latest yaspeller, Working with local yaspeller ${RESET}"
we are replaying on it with the docker file.
but i can push it in to this repo

2021-04-28 07:39 UTC, eifrach commented on Makefile
> +## Build image localhost/kubevirt.io
adding change

2021-04-28 07:39 UTC, eifrach commented on Makefile
> +	${CONTAINER_ENGINE} run -it --rm --name yaspeller -v ${PWD}:/srv:ro${SELINUX_ENABLED} -v /dev/null:/srv/Gemfile.lock --workdir=/ ${IMGTAG} /bin/bash -c 'yaspeller -c /srv/.yaspeller.json --only-erro
adding change

2021-04-28 07:39 UTC, eifrach commented on Makefile
> +	@echo "${GREEN}Makefile: Check Container status${RESET}"
adding change

2021-04-28 07:39 UTC, eifrach commented on Makefile
>  	@echo "${GREEN}Makefile: Stop site${RESET}"
adding change

2021-04-28 07:52 UTC, eifrach commented on Makefile
> +	${DEBUG} curl $${REPOPATH}/update-yaspeller.sh | bash -  > /dev/null  2>&1 || echo "${YELLOW} Cannot get latest yaspeller, Working with local yaspeller ${RESET}"
added changes

2021-04-28 13:54 UTC, mazzystr commented
@eifrach This is a much cleaner pull req.  Thanks for recreating it.  

Since we're changing the way the Makefile works we need to update the README.md to reflect those changes.  Please add a commit for that.

Then all there is just a few minor changes that need fixed.


More on L161 .... I'm gonna insist that the old script get put back.  I had to do locally in order to test `make check_spelling` since otherwise I can't test until the CI team takes a look and merges pull/115.  In the future if we want to expand the script we have to check it in to project repo ... then test here.  That's a pretty bad dependency.  We also have to bolt on additional script functions such as `|` and `||` to get around file system permissions and give a problem notice to the user.  We're in the exact same spot as before with additional complexity and risk.

If you put the old script back we can merge this pretty quick when the minors get fixed.  

We can talk about consolidating all the file retrieve code in another issue/pull_req.

2021-04-29 13:04 UTC, eifrach commented
@mazzystr all changes has been added

2021-05-11 21:24 UTC, mazzystr commented
/test kubevirt-io-presubmit-link-checker

2021-05-11 21:32 UTC, merged