Update README
kubevirt/kubevirt.github.io pull request #748
Opened 2021-06-11 16:43 UTC by mazzystr

**What this PR does / why we need it**:
Update README to reflect new development process

**Special notes for your reviewer**:
@cwilkers  @jobbler  Please do a thorough review and tag /lgtm before David tags for approval.  Thanks.

2021-06-11 19:05 UTC, cwilkers requested changes
I suggested some optional changes for improved flow

2021-06-11 19:05 UTC, cwilkers commented on README.md
> +To sync from upstream I do the following ... but be careful here.  This slams the door hard on existing code. You can lose data.
A less familiar way to write:

Note this will overwrite any files in the master branch. Make sure all work is done in local branches, and leave the master branch only for tracking the upstream repository.

2021-06-11 21:15 UTC, jobbler commented on README.md
> +```
```suggestion
Your local git repo will have a remote alias called `origin` which points to your fork in GitHub.  Our repositories have many contributors and you will need to periodically synchronize your local copy and forked copy with the original projects repository.
The repository of the original project is typically called `upstream`.  Adding a remote alias to the original project can make it easier to keep the forked repository and local copies synchronized.

Add an additional remote alias called upstream using the following command:

```bash
git remote add upstream clone_line_from_the_code_button_earlier
```
```

2021-06-11 21:15 UTC, jobbler commented on README.md
> +To sync from upstream I do the following ... but be careful here.  This slams the door hard on existing code. You can lose data.
I would rewrite this as @cwilkers suggested.

2021-06-11 21:15 UTC, jobbler commented on README.md
> +#### rebase
```suggestion
#### Rebase
```

2021-06-11 21:15 UTC, jobbler commented on README.md
> +We have the ability to run the same  tests locally as in CI.  This saves time from having to go through the  process just to find out the pull_req has a problem that prevents merge.
```suggestion
We have the ability to run the same tests locally that are run in CI.  This saves time from having to go through the  process just to find out the pull_req has a problem that prevents merge.
```

2021-06-11 21:21 UTC, mazzystr commented on README.md
> +We gladly welcome contributions or please reach out if you happen to have an idea or find an issue with our contents.  [Here's our guidelines for contents](GUIDELINES.md).
ok

2021-06-11 23:41 UTC, mazzystr commented on README.md
> +```bash
We're good here.  The markdown processors used here is GitHub only

2021-06-14 21:06 UTC, cwilkers commented on README.md
> +There is always a strong possibility for merge conflicts. Proceed with caution in resolving. Each conflict must be hand editted. Perform the following to resolve each conflict ...
Edited

2021-06-14 21:12 UTC, cwilkers commented on README.md
> +There is always a strong possibility for merge conflicts. Proceed with caution in resolving. Each conflict must be hand editted. Perform the following to resolve each conflict ...
Looks good after one more spell check to catch that "editted"

2021-06-18 17:34 UTC, cwilkers requested changes
More edits! Looking good!

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +To clone the forked repository locally web browse to https://www.github.com/*you*/kubevirt.github.io. Click the `Code` button. Select the clone method and copy the url to clipboard. Open a terminal w
```suggestion
To clone the forked repository locally, browse to your fork at https://www.github.com/*you*/kubevirt.github.io. Click the `Code` button. Select the clone method and copy the url to clipboard. Open a terminal window and  ...
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +By default the local git repo will have a remote alias called `origin` that points to your fork in GitHub. KubeVirt repositories have many contributors  work needs to be done periodically to synchron
```suggestion
By default the local git repo will have a remote alias called `origin` that points to your fork in GitHub. KubeVirt repositories have many contributors so work needs to be done periodically to synchronize local and origin branches with upstream branches. To enable this work flow on your local clone, add a new remote to the repository. By convention, this remote is named `upstream`.
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +To sync upstream master branch from upstream perform the following ...
```suggestion
To sync the master branch from the upstream repository, perform the following ...
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +If you are a UI/UX developer help with the structure and layout of the website is definitely needed. Feel free to browse [website issues](https://github.com/kubevirt/kubevirt.github.io/issues?q=is%3A
```suggestion
If you are a UI/UX developer, the structure and layout of the website would greatly benefit from your attention. Feel free to browse [website issues](https://github.com/kubevirt/kubevirt.github.io/issues?q=is%3Aopen+is%3Aissue+label%3Akind%2Fwebsite) or contribute other ideas.
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +The ability to run the same tests locally as in CI is available via the included Makefile. This saves time from having to go through the process just to find out the pull req has a problem that preve
```suggestion
The Makefile at the base of this repository provides editors the ability to locally run the same tests CI uses to validate changes. This saves time over waiting for online CI resources to spin up just to find out a pull request has a problem that prevents merge.
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +If you discover an error that should not be an error feel free to add the offending word to the dictionary file located at GitHub repo `kubevirt/project-infra/images/yaspeller/.yaspeller.json`
```suggestion
If you discover a flagged spelling error that you believe is not a mistake, feel free to add the offending word to the dictionary file located at GitHub repo `kubevirt/project-infra/images/yaspeller/.yaspeller.json`. Try to keep the dictionary file well ordered, and employ regular expressions to handle plurals and typical conjugations.
```

2021-06-18 17:34 UTC, cwilkers commented on README.md
> +5) Create a nice subject and body for the pull request and click the "Create pull request" button.
```suggestion
5) Create a nice subject and body for the pull request, be sure to tag any related issues, and click the "Create pull request" button.
```

2021-06-21 17:09 UTC, mazzystr commented
/test kubevirt-io-presubmit-link-checker

2021-06-21 17:14 UTC, cwilkers commented
I've gone over the latest changes and everything appears well.

2021-06-21 20:03 UTC, davidvossel reviewed
/approve

2021-06-22 16:08 UTC, mazzystr commented
/lgtm

2021-06-22 16:54 UTC, davidvossel commented
/lgtm

2021-06-22 16:55 UTC, merged