New KubeVirt Live Migration Lab
kubevirt/kubevirt.github.io pull request #752
Opened 2021-06-23 19:13 UTC by cwilkers

- Added new lab to toc
- Added new quickstart include for multinode minikube
- Added example vm with masquerade network
- Added scriptlets for:
  - live migration feature gate
  - port exposure
  - netcat http server while loop
  - tests for http

Signed-off-by: cwilkers <cwilkers@redhat.com>

2021-06-24 16:59 UTC, mazzystr commented
/ok-to-test

2021-06-25 14:19 UTC, cwilkers commented
Following a conversation on the kubevirt-dev mailing list, I am considering including labs/manifests/vm.yaml in this PR, changing its network style to masquerade, and re-using this yaml for this PR rather than duplicating it in a code scriptlet.

2021-06-25 16:32 UTC, mazzystr requested changes

2021-06-25 16:32 UTC, mazzystr commented on labs/kubernetes/migration.md
> +```
L25-65 should be removed.  Provider information isn't to the lab.  I could compromise with an annotation stating Live Migration reqs two or more nodes and a properly configured sdn.

2021-06-25 18:05 UTC, mazzystr commented
Everything looks great!  We're rolling!

/lgtm
/approve

2021-06-25 18:11 UTC, merged

2021-06-29 19:28 UTC, cwilkers commented
Fixed #759

2021-06-29 19:31 UTC, cwilkers commented
Fixed #760