Update index page
kubevirt/kubevirt.github.io pull request #762
Opened 2021-07-03 00:58 UTC by mazzystr

Add adopters (end-users, vendors, integrations) list to index page
Add adopters data file
Fix footer toolbox pop ups

TESTING.... Scroll down main page
* Spacing should look pleasant
* There should be tables with 0 px borders
* Each adopter table should have a center justified title for end-users, vendors and integrations
* Side quest ... hover mouse over social media icons in footer .... toolbox should appear displaying what they are.

@matthewcarleton Could you please review and comment a /lgtm if it looks good to you?  Thanks!

2021-07-03 01:57 UTC, mazzystr commented
@jberkus

2021-07-05 16:08 UTC, matthewcarleton reviewed
just a few comments

2021-07-05 16:08 UTC, matthewcarleton commented on index.html
> +    <a href="{{ enduser.url }}">
I would add all your css to the link and not the image.

2021-07-06 15:58 UTC, mazzystr commented on index.html
> +    <a href="{{ enduser.url }}">
I tried and it breaks everything.  imgs are no longer able to be found per jekyll logs.

Is that a cosmetic change or do we gain some kind of functionality?

2021-07-06 16:00 UTC, mazzystr commented on _includes/footer.html
>        <p class="text-md-right">
This isn't part of my diff.  It's been in place for a very long time.  I don't think I should mess with it here....

per git blame .....
```
e3a8e49320 (Adam Jolicoeur     2018-07-01 09:47:38 -0400  8)       <p class="text-md-right">
```

2021-07-06 17:12 UTC, matthewcarleton commented on _includes/footer.html
>        <p class="text-md-right">
oh whoops - ya let's not poke the bear :)

2021-07-06 17:12 UTC, matthewcarleton commented on index.html
> +    <a href="{{ enduser.url }}">
can you show me the code you wrote? hard to tell what's going wrong here

2021-07-06 19:40 UTC, mazzystr commented on index.html
> +    <a href="{{ enduser.url }}">
I must have had some mistake.  Missing quote or something.  It's working now.

2021-07-06 20:34 UTC, matthewcarleton reviewed
css is fun :)

2021-07-06 20:34 UTC, matthewcarleton commented on _sass/_layout.scss
> +  gap: 2rem;
do you need this?

2021-07-06 20:34 UTC, matthewcarleton commented on _sass/_layout.scss
> +  img { width: 200px; height: auto; }
do you need the height?

2021-07-06 20:34 UTC, matthewcarleton commented on _sass/_layout.scss
> +  gap: 2rem;
lots of repeating css here maybe have one class for all the same styles

2021-07-06 20:34 UTC, matthewcarleton commented on _sass/_layout.scss
> +  gap: 2rem;
there's some overlapping with the <a> - I'd add some margin in there, probably the simplest fix rather than rewriting all the grid css for the layout.

2021-07-06 21:00 UTC, mazzystr commented
/hold

Waiting on approval from Red Hat, Suse, Rancher, H3C, Cloudflare, CIVO, CoreWeave, Kubermatic

2021-07-06 22:12 UTC, mazzystr commented on _sass/_layout.scss
> +  img { width: 200px; height: auto; }
Nope.  I removed it.

2021-07-06 22:21 UTC, mazzystr commented on _sass/_layout.scss
> +  gap: 2rem;
Nope!

2021-07-06 23:04 UTC, mazzystr commented on _sass/_layout.scss
> +  gap: 2rem;
I like having separate classes for each row.  It allows for fine tuned spacing.

2021-07-06 23:17 UTC, salanki commented
Approved from CoreWeave
/lgtm

2021-07-07 08:13 UTC, mfranczy commented
Approved from Kubermatic
/lgtm

2021-07-08 07:38 UTC, AlexsJones commented
Approved from Civo
/lgtm

2021-07-08 11:55 UTC, vasiliy-ul commented on _data/adopters.yml
> +      logo: SUSE.png
please use the official logo from https://brand.suse.com/. there you can find versions for horizontal/vertical layout and dark/light background.

2021-07-08 16:17 UTC, mazzystr commented on _data/adopters.yml
> +      logo: SUSE.png
File is updated.  Please validate.  url is here ... https://deploy-preview-762--kubevirtio.netlify.app/

2021-07-09 05:09 UTC, poojaghumre commented
Approved from Platform9
/lgtm

2021-07-09 10:44 UTC, dirkmueller commented on _data/adopters.yml
> +      logo: SUSE.png
this looks great, thanks @mazzystr

2021-07-09 10:45 UTC, dirkmueller commented
Approved from SUSE side
/lgtm

2021-07-09 14:11 UTC, vielmetti commented
@mazzystr - received an email from you regarding approving a change to this page, but I'm not seeing any sign of an Equinix Metal logo or reference in the diffs provided.

For reference, our brand guidelines are here https://brand.equinix.com/

2021-07-09 15:33 UTC, mazzystr commented
> @mazzystr - received an email from you regarding approving a change to this page, but I'm not seeing any sign of an Equinix Metal logo or reference in the diffs provided.
> 
> For reference, our brand guidelines are here https://brand.equinix.com/

@vielmetti Equinix is added.  Validation url is here... https://deploy-preview-762--kubevirtio.netlify.app/

2021-07-09 15:49 UTC, vielmetti commented
@mazzystr I've asked our marketing people to take a look. The only thing I note is that the logo looks fuzzy - if there's a specific dimension that you need, I think we can create it for you from the original vectors so that it's sharp.

2021-07-09 16:03 UTC, vielmetti commented
@mazzystr - based on feedback from our marketing, two requests.

One, please use the vertically aligned "Equinix Metal" logo at https://github.com/packethost/metal-logo/blob/main/Vertical/Full%20Color/Equinix%20Metal%20Vertical%20RGB.png . That directory has a lot of formats, I'm guessing that the PNG is the best.

Second, please use the link "https://metal.equinix.com" instead of "https://equinix.com" as the click through.

2021-07-09 16:18 UTC, mazzystr commented
@vielmetti Logo and link updated. and thank you for that nicely sized logo.  I was starting to sweat trying to figure out how to resize with css.  ;-)  Preview link is here ... https://deploy-preview-762--kubevirtio.netlify.app/

2021-07-09 16:21 UTC, vielmetti commented
Approved from Equinix Metal, thanks!
/lgtm

2021-07-12 18:46 UTC, chrisj-platform9 commented
Approved from Platform9. Thanks team.

2021-07-21 19:30 UTC, fabiand commented
@rthallisey who can help to approve for nvidia?

2021-07-21 19:31 UTC, fabiand requested changes

2021-07-21 19:31 UTC, fabiand commented on _data/adopters.yml
> +    - name: KUBERMATIC
Kubermatic is a vendor unless I am mistaken

2021-07-22 07:53 UTC, mfranczy commented on _data/adopters.yml
> +    - name: KUBERMATIC
yup vendor, you're right

2021-07-22 20:30 UTC, mazzystr commented
@rthallisey  please review and make a comment of approval ... https://deploy-preview-762--kubevirtio.netlify.app

2021-07-22 20:33 UTC, mazzystr commented on _data/adopters.yml
> +    - name: KUBERMATIC
Fixed

2021-07-22 21:54 UTC, rthallisey commented
/lgtm from NVIDIA

2021-08-24 01:48 UTC, mazzystr commented
@jberkus I think we have a great list so far and we should ship this pull req asap.  I'm can split out Rancher, H3C, Cloudflare, and StackPath into their own issues.  I will hunt down their representatives and obtain approval individually.

2021-08-25 11:47 UTC, stu-gott reviewed
/lgtm
/approve

Given previous comment to search out other representatives individually I think the list of approvals needed for this PR is complete.

2021-08-25 14:05 UTC, stu-gott commented
/hold cancel
No need to hold at this point

2021-08-25 14:12 UTC, merged