Blog post about VMs with Istio
kubevirt/kubevirt.github.io pull request #769
Opened 2021-08-11 08:08 UTC by rhrazdil

Add a blog post introducing KubeVirt support for Istio.

Blog post demonstrates running VMs and monitoring collected
traffic metrics using kubevirtci ephemeral cluster.

Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

2021-08-16 10:16 UTC, maiqueb requested changes
I especially like the structure of the post.

Despite that, I got some suggestions I think improve the overall readability of the post.

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +traffic metrics can be observed in Kiali dashboard for `istio-vmi`.
This reads well enough, but I think it would be better as (not sure the suggestion below can be easily understood; I propose to just make the 2 last paragraphs entries of a list):

```suggestion
To demonstrate monitoring and tracing capabilities, we will create two VMIs within Istio service mesh: 
- `istio-vmi` repeatedly requests external HTTP service kubevirt.io, and serves a simple HTTP server on port 8080.
- `Cirros-vmi` repeatedly request the HTTP service running on the `istio-vmi` VMI. With this topology setup, both inbound and outbound traffic metrics can be observed in Kiali dashboard for `istio-vmi`.
```

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +To create an Istio aware virtual machine the `sidecar.istio.io/inject: "true"` annotation needs to be specified.
```suggestion
An Istio aware virtual machine **must be** annotated with `sidecar.istio.io/inject: "true"`.
```

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Notice the virt-launcher pod having 3/3 containers. The extra container is the istio proxy.
I somehow find the sentence to be off.. 

What do you think about:

"After creating the VMI, the corresponding virt-launcher pod should have 3 ready containers, as shown in the snippet below:"  ?

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +**Note:** it may take a few moments for the VMs to be fully booted up and the traffic picked up in Kiali dashboard.
While I'm perfectly fine with this note, you could instead show the command for the VMI to be ready (or have a readiness probe on your VMI spec :) ). 

Either would be, imho, more complete - but also more complex.

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +
nit: extra empty line (iiuc).

2021-08-16 10:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This blog post covered running KubeVirt virtual machine in Istio service mesh using an ephemeral kubevirtci cluster. Kiali dashboard was used to observe inbound and outbound traffic of a virtual mach
I really like the conclusion.

2021-08-17 12:58 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Istio is configured to install with CNI plugin in our ephemeral k8s cluster, which allows running the sidecar without NET_ADMIN and NET_RAW capabilities.
> I'm assuming this CNI does whatever it was the sidecar did that required those capabilities, but I honestly find this off-putting.

Correct, I'll remove this

2021-08-17 15:09 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +
Removed

2021-08-17 15:10 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +**Note:** it may take a few moments for the VMs to be fully booted up and the traffic picked up in Kiali dashboard.
Thanks for the suggesting, that's neat.
Added the readiness probe and reoredred the text a bit - creating all VMIs first and then waiting and checking that all is good.

2021-08-17 15:10 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Notice the virt-launcher pod having 3/3 containers. The extra container is the istio proxy.
I like your suggestion, done

2021-08-17 15:10 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +To create an Istio aware virtual machine the `sidecar.istio.io/inject: "true"` annotation needs to be specified.
Done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +traffic metrics can be observed in Kiali dashboard for `istio-vmi`.
Done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +The NetworkAttachmentDefinition spec is empty, as the only purpose of it is to invoke the istio-cni binary, which handles configuration of the in-pod traffic routing.
Done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Since our ephemeral k8s cluster has multus installed, there needs to be NetworkAttachmentDefinition called `istio-cni` created in each namespace where Istio sidecar containers are to be used:
Done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +
Removed

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Enable automatic sidecar injection by adding `istio-injection=enabled` label to target namespace:
Thanks, done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +kubectl create -f istio-1.10.0/samples/addons/prometheus.yaml
I think it looks better, done

2021-08-17 15:11 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +If you want to see exact Istio configuration, follow [this link](https://github.com/kubevirt/kubevirtci/blob/2108081530-91f55e3/cluster-provision/k8s/1.21/istio.sh).
Done

2021-08-17 15:12 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This allows the sidecar to not only collect metadata about the proxied traffic but also actively interfere with it if so configured.
Please, see if the current version is better

2021-08-17 15:12 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +injecting a proxy container, a so called sidecar, which forwards traffic that goes in and out of a pod/virtual machine.
Done

2021-08-17 15:14 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +tags: [kubevirt, istio, virtual machine, VM, service mesh, mesh]
That's pretty much what I did with the keywords, except for the istio, service mesh, mesh. Those are my invention.
I'm not completely sure what's the point of the tags, it doesn't seemt o be used to group articles by them and whether it's used by serach engine I have no idea.

2021-08-18 09:10 UTC, maiqueb approved these changes
I haven't followed the steps on the post, but I do expect someone to make sure the post works when followed.

I can follow the guide step by step and check its accuracy at a later date pre-merge if no one else can spare the time.

2021-08-18 09:10 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +tags: [kubevirt, istio, virtual machine, VM, service mesh, mesh]
I'll leave this possible action point to someone that understands how we are using tags in the blog posts.

2021-08-18 09:10 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +`Istioctl proxy-status` should report that the sidecar proxies running inside the virt-launcher pods have synced with Istio control plane:
```suggestion
`Istioctl proxy-status` should report the sidecar proxies running inside the virt-launcher pods have synced with Istio control plane:
```

nit: I think the `that` is redundant.

2021-08-18 09:10 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +For example, the sidecar may inject faulty HTTP responses or delay them, load balance traffic between different versions of an application or mirror traffic for testing/debugging purposes.
```suggestion
For example, the sidecar may inject faulty HTTP responses (or delay them), load balance traffic between different versions of an application, or mirror traffic for testing/debugging purposes.
```

Nit: I just get confused about and / or in big sentences.

2021-08-18 10:16 UTC, maiqueb approved these changes
Thanks.

2021-08-23 09:41 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +git reset 656b60bc114d592b77b5a25b42dbec2801f9b882 --hard
This is not working for me. 

And I have to ask: why hard reset vs checkout ?

2021-08-23 10:33 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +git reset 656b60bc114d592b77b5a25b42dbec2801f9b882 --hard
I followed [this post](https://github.com/kubevirt/kubevirt.github.io/blob/master/_posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown#demo-environment-setup) which used reset, but you're right, checkout tag makes more sense.

Fixed the tag

2021-08-23 10:58 UTC, phoracek requested changes

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This allows the sidecar to collect metadata about the proxied traffic and also actively interfere with it.
The following line (which I cannot comment on for some reason) mentions testing/debugging features by it misses one of the main ones - ability to perform traffic shaping, model the allowed communication graph

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
CNAO is needed for Multus? Would it be worth mentioning it in the list of prerequisites? In case somebody tries this on their own cluster. And maybe mentioning Istio there too.

The idea being - prerequisites mention all the needed components to run it anywhere, but this section helps you set it up in a controlled environment

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +### Install Istio addons
Maybe we should have one for Multus too? Again, I'm not sure if it would be better, just spitting thoughts...

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Download istio manifests and client binary by running the following command:
Istio with capital I? So it is consistent in the whole article

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +- requests from `cirros-vmi` to `istio-vmi` via `istio-vmi-svc`service,
```suggestion
- requests from `cirros-vmi` to `istio-vmi` via `istio-vmi-svc` service,
```

2021-08-23 10:58 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +## Conclusion
Should we link to the user-guide?

2021-08-23 11:04 UTC, maiqueb reviewed
Just minor things, other reviewers can approve / lgtm away.

I **can confirm** the guide works as described.

2021-08-23 11:04 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +virt-launcher-istio-vmi-99t8t.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-nk4cd     1.10.0
For whatever reason, I get more that these 2: 

```bash
$ istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          ISTIOD                      VERSION
istio-egressgateway-55d4df6c6b-qcllf.istio-system      SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7d96484d6b-b74pd     1.10.0
istio-ingressgateway-69dc4765b4-pdn68.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-7d96484d6b-b74pd     1.10.0
virt-launcher-cirros-vmi-r77sn.default                 SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-b74pd     1.10.0
virt-launcher-istio-vmi-jgk59.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-b74pd     1.10.0

```

2021-08-23 11:04 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
>  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
I use zsh, and as such, I had to enclose the URLs in double-quotes. Consider this.

2021-08-23 11:12 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
> CNAO is needed for Multus? Would it be worth mentioning it in the list of prerequisites? In case somebody tries this on their own cluster. And maybe mentioning Istio there too.
> 
> The idea being - prerequisites mention all the needed components to run it anywhere, but this section helps you set it up in a controlled environment

I don't think CNAO is needed. It is just a convenient way on kubevirtci to deploy it. Adding it to the requirements feels like lying, imo.

This might actually raise the question if we want to have CNAO here vs install multus as per [their documentation](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md#installation).

You could even just add:
```bash
kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/images/multus-daemonset.yml
```

2021-08-23 11:16 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This allows the sidecar to collect metadata about the proxied traffic and also actively interfere with it.
I had "put" that in the "collect metada about the proxied traffic" meta-bucket. Definitely deserves a shout-out.

2021-08-23 11:35 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
It's not needed, I used it to show the more complicated setup, that involves creating a NAD.

> EDIT: do we need any other cni plugin shipped via cnao ?... I might have spoken too soon.

no we don't, I simply used cnao to have multus for the reson above.

If having multus feels out of focus, we can take it out of the picture along with cnao.
The linked [install script](https://github.com/kubevirt/kubevirtci/blob/2108081530-91f55e3/cluster-provision/k8s/1.21/istio.sh) for Istio would still provide complete information about Istio configuration.

We may also keep the Network attachment definition section just to informing that `with multus, this CNI needs to be created...`

2021-08-23 11:53 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +virt-launcher-istio-vmi-99t8t.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-nk4cd     1.10.0
I have ommited the gateways on purpose to not bloat the output with default istio resources.
If you think it may cause confusion, I would include them

2021-08-23 11:55 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
I'm slightly leaning towards your option to mention NAD but don't make it a part of the demo. Just to keep it slim.

2021-08-23 12:22 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
I am actually against that. Keeping the steps required for secondary networks is important, imo.

You might want to provide a separate section for it though, so readers understand better that this is only required for secondary networks.

As a side note: I like how it currently is.

2021-08-23 12:24 UTC, maiqueb commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +virt-launcher-istio-vmi-99t8t.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-nk4cd     1.10.0
I would be OK with a tiny note indicating that you're only showing the relevant entities. 

Does that make sense ?

2021-08-23 12:26 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +export KUBEVIRT_WITH_CNAO=true
I don't insist on it being changed neither. Let's keep it as is then

2021-08-23 12:39 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +## Conclusion
Linked

2021-08-23 12:39 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +- requests from `cirros-vmi` to `istio-vmi` via `istio-vmi-svc`service,
Thanks! Fixed

2021-08-23 12:40 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +Download istio manifests and client binary by running the following command:
Fixed

2021-08-23 12:41 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This allows the sidecar to collect metadata about the proxied traffic and also actively interfere with it.
@phoracek would you please take a look if this formulation is better in tha [last commit](https://github.com/kubevirt/kubevirt.github.io/pull/769/commits/636e35d10d02aff62209310e9e1fa7c06cb4ddb1)?

2021-08-23 12:42 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +### Install Istio addons
I think, with regards to the above [discussion](https://github.com/kubevirt/kubevirt.github.io/pull/769#discussion_r693867540), this is not needed?

2021-08-23 12:42 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +virt-launcher-istio-vmi-99t8t.default                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-7d96484d6b-nk4cd     1.10.0
Sure, added a note

2021-08-23 12:42 UTC, rhrazdil commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
>  kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
Thanks, added

2021-08-23 14:29 UTC, maiqueb commented
From my perspective, all is well - I'll refrain from adding lgtm so @phoracek can express his compliance w/ the post.

2021-08-23 14:48 UTC, phoracek requested changes
Last minor comments for consistency sake.

2021-08-23 14:48 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This allows the sidecar to collect metadata about the proxied traffic and also actively interfere with it.
Looks good, thanks

2021-08-23 14:48 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +### Run k8s cluster
```suggestion
### Run Kubernetes cluster
```

2021-08-23 14:48 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +This involves adding a label and creating a NetworkAttachmentDefinition in the target namespace.
```suggestion
This involves adding a label and creating a `NetworkAttachmentDefinition` in the target namespace.
```

2021-08-23 14:48 UTC, phoracek commented on _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
> +When multus is installed in k8s cluster, a `NetworkAttachmentDefinition` called `istio-cni` **must** be created in **each** namespace where Istio sidecar containers are to be used:
```suggestion
When Multus is installed in k8s cluster, a `NetworkAttachmentDefinition` called `istio-cni` **must** be created in **each** namespace where Istio sidecar containers are to be used:
```

2021-08-24 12:29 UTC, phoracek approved these changes

2021-08-24 12:34 UTC, phoracek commented
/approve

2021-08-24 14:31 UTC, maiqueb commented
For completeness, or just to compare, you might want to link part of [this blog post](https://medium.com/open-5g-hypercore/episode-iii-meshville-7f0bb7ca0e3b). 

The `Background` / `Networking Under The Hood` sections have valuable (but honestly also very deep) information.

Again: I'm good with the current post - I just happened to stumble upon this.

2021-08-25 07:10 UTC, maiqueb commented
/lgtm

2021-08-25 15:43 UTC, phoracek commented
/approve

2021-08-25 15:49 UTC, merged