First attempt at a data driven adopters consumed from kubevirt/kubevirt
kubevirt/kubevirt.github.io pull request #797
Opened 2021-09-10 19:21 UTC by mazzystr

Signed-off-by: Chris Callegari <mazzystr@gmail.com>

/kind/enhancement

**What this PR does / why we need it**:
ADOPTERS list is getting out of hand  We have kubevirt/kubevirt:ADOPTERS.md, kubevirt/kubevirt:~/_data/adopters.yml, Karena's doc with a list of adopters.  We also have adopters scattered throughout the project via mailing list subscription, slack membership, pull req creation, YouTube video publishing, Blog publishing.

Let's start to get a handle on this and consolidate all adopters to `kubevirt/kubevirt:ADOPTERS.md`... See [kubevirt/kubevirt/pull/6385](https://github.com/kubevirt/kubevirt/pull/6385).  Then we can use `adopters.py` to populate a yaml file that the jekyll engine can use to build the index.html file for the website.

Note: https://github.com/kubevirt/kubevirt/pull/6385 should be merged before this merges

2021-09-13 15:46 UTC, jobbler requested changes

2021-09-13 15:46 UTC, jobbler commented on _data/adopters.py
> +with open('../../kubevirt/ADOPTERS.md','r') as f:
We should be able to pull this straight from the github.com repo instead of a local copy. I think it would be safer than usiong a potentially modified local copy.

2021-09-13 15:46 UTC, jobbler commented on _data/adopters.py
> +g.write(yaml.dump(x))
Can something be added to tell the user what to do next?

Also, add a note in the yaml to tell people to not modify the adopters.yml manually and to modify the ADOPTERS.md and run this script.

2021-09-14 00:25 UTC, mazzystr commented on _data/adopters.py
> +with open('../../kubevirt/ADOPTERS.md','r') as f:
Done!

2021-09-14 00:34 UTC, mazzystr commented on _data/adopters.py
> +g.write(yaml.dump(x))
@jobbler  This update should work.  Let me know what you think

2021-09-14 00:36 UTC, jobbler commented
@mazzystr thanks for making the changes.
/lgtm

2021-09-14 16:35 UTC, cwilkers commented
/retest

2021-09-14 19:09 UTC, cwilkers approved these changes
/approve

2021-09-14 19:16 UTC, mazzystr commented
The script works 100% as is.  We can manually update adopters.yml manually since we have a lot of eyes on kubevirt/kubevirt ADOPTERS right now.

We will address automation in a future pull req.

I'm removing the hold tag so that we can rebase/merge when the link gets fixed via the istio pull.

2021-09-14 19:51 UTC, cwilkers commented
/lgtm

2021-09-14 19:53 UTC, merged