blog: add post about dedicated migration networks
kubevirt/kubevirt.github.io pull request #826
Opened 2022-01-25 21:23 UTC by jean-edouard

**What this PR does / why we need it**:
This PR adds a blog post about dedicated migration networks.

2022-01-25 23:50 UTC, cwilkers requested changes
Thank you for your blog post!

I've included some suggestions in review.

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +description: KubeVirt now supports using a separate network for live migrations
You're missing some lines, so the post did not render properly.

```suggestion
---
layout: post
author: Jed Lejosne
description: KubeVirt now supports using a separate network for live migrations
```

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Since version 0.49, KubeVirt supports live migrating VMIs over a separate network than the one kubernetes is running on.
```suggestion
Since version 0.49, KubeVirt supports live migrating VMIs over a separate network than the one Kubernetes is running on.
```

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Important: the subnet used here must be completely distinct from the one used by the main kubernetes network, to ensure proper routing.
Here, I'm thinking it's worth switching to plural to point out we should be distinct from both the cluster CIDR and the Pod CIDR
```suggestion
Important: the subnet used here must be completely distinct from the ones used by the main Kubernetes network, to ensure proper routing.
```

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +The KubeVirt custom resource is then editted to enable live migrations and define which NAD to use for migrations. That edit triggers a restart of the virt-handler pods.
Spelling, but you might consider whether it would be helpful to cross-link 'enable live migrations' to the feature-gate documentation.

```suggestion
The KubeVirt custom resource is then edited to enable live migrations and define which NAD to use for migrations. That edit triggers a restart of the virt-handler pods.
```

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Looking at one of the new virt-handler pods, we can see it now connected to the migration bridge, and got an IP from whereabouts.
```suggestion
Looking at one of the new virt-handler pods, we can see it is now connected to the migration bridge with an IP from whereabouts.
```

2022-01-25 23:50 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Here is a quick [example](https://asciinema.org/a/464272) of a dual-node KubeVirtCI cluster running a migration over a secondary network.
I would recommend adding some code examples to this section, as you're going into some detail to explain what happens in the asciinema video. Nothing too lengthy should be required, just some of the output you're referring to.

This would also help if the asciinema expires at some point in the future, to ensure the blog still contains the info.

2022-01-26 13:14 UTC, jean-edouard commented on _posts/2022-01-25-Dedicated-migration-network.md
> +description: KubeVirt now supports using a separate network for live migrations
Will do! Out of curiosity, how do you see the rendering of an open PR?
Thanks for the review!

2022-01-26 13:23 UTC, jean-edouard commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Here is a quick [example](https://asciinema.org/a/464272) of a dual-node KubeVirtCI cluster running a migration over a secondary network.
I was trying to avoid any code to keep the post light and easy to read.
The commands used in the asciinema are pretty basic, and example yamls can be found in the documentation.
Finally, I linked the clip to an asciinema account so it doesn't get archived (this time!)
I copy-pasted this whole section to the description of the asciinema clip, maybe I should just remove it from here and just have a link to the clip?

2022-01-26 14:55 UTC, cwilkers commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Here is a quick [example](https://asciinema.org/a/464272) of a dual-node KubeVirtCI cluster running a migration over a secondary network.
Moving this discussion to the clip makes sense, I was just thinking it helps to have the relevant piece of code present when you're discussing what happens.

Another possible path would be to link to snippets of the asciinema so they show up inline in the blog. (I've seen this before on other pages, but have no idea how do set it up -- asciinema is on my list of things I ought to go learn.

2022-01-26 15:21 UTC, jean-edouard commented on _posts/2022-01-25-Dedicated-migration-network.md
> +description: KubeVirt now supports using a separate network for live migrations
Nice, got it, thanks!

2022-01-26 15:22 UTC, jean-edouard commented on _posts/2022-01-25-Dedicated-migration-network.md
> +Here is a quick [example](https://asciinema.org/a/464272) of a dual-node KubeVirtCI cluster running a migration over a secondary network.
Done

2022-02-16 15:25 UTC, jean-edouard commented
@cwilkers could you please take another look to see if your concerns are addressed? Thank you!

2022-02-16 18:02 UTC, cwilkers approved these changes
/lgtm
/approve

2022-02-16 18:11 UTC, merged