[DNM] Load-balancer for VirtualMachines on bare metal Kubernetes clusters
kubevirt/kubevirt.github.io pull request #837
Opened 2022-04-03 14:23 UTC by RamLavi

**What this PR does / why we need it**:

**Special notes for your reviewer**:

2022-04-04 10:00 UTC, RamLavi commented
/hold

still needs a few adjustments, but structure wise this is sound

2022-04-04 10:54 UTC, phoracek requested changes

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Over the last year, kubevirt has integrated with MetalLB in order to support fault-tolerant access to an application
```suggestion
Over the last year, KubeVirt has integrated with MetalLB in order to support fault-tolerant access to an application 
```

I believe that when we refer to the KubeVirt project, we use the CapitalSnakeCase

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +through an external IP address. As a Cluster administrator using a bare-metal cluster, now it's possible to add MetalLB
Is not the use-case for MetalLB on-premise clusters? Baremetal servers can be deployed in public cloud too.

@fedepaol please keep me honest here

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +implementation in clusters that don’t run on a cloud provider, such as bare-metals.
bare-metals can run on a cloud provider

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +the local network. This method announces the IPs in ARP (for IPV4) and NDP (for IPV6) protocols over the network. From a
```suggestion
the local network. This method announces the IPs in ARP (for IPv4) and NDP (for IPv6) protocols over the network. From a 
```

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +- BGP mode
This renders as a single paragraph "BGP mode BGP mode provides..."

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To read more on MetalLB concepts, implementation and limitations, please read [here](https://metallb.universe.tf/concepts/).
```suggestion
To read more on MetalLB concepts, implementation and limitations, please read [its documentation](https://metallb.universe.tf/concepts/).
```

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +With the following recipe we will end up with a nginx server running on a virtualMachine, accessible outside the cluster
```suggestion
With the following recipe we will end up with a nginx server running on a virtual machine, accessible outside the cluster 
```

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +using MetalLB loadBalancer.
```suggestion
using MetalLB load balancer.
```

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To start it up follow this [guide](https://kind.sigs.k8s.io/docs/user/quick-start)
```suggestion
To start it up follow this [guide](https://kind.sigs.k8s.io/docs/user/quick-start).
```

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +We are going to use [kind](https://kind.sigs.k8s.io) provider as an ephemeral Kubernetes cluster.
That's a very long guide, do I need to follow the Advanced part? Or build my own images?

Please mention which parts of the quick start should I follow

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Now it's time to start-up a virtualMachine running nginx, using this yaml:
The colon is confusing here

2022-04-04 10:54 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +### Expose the virtualMachine with a typed LoaBalancer service
```suggestion
### Expose the VirtualMachine with a typed LoaBalancer service 
```

2022-04-04 12:02 UTC, fedepaol commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +through an external IP address. As a Cluster administrator using a bare-metal cluster, now it's possible to add MetalLB
Both "on premise" and "baremetal" may be non 100% correct (because there can be distributions deploy-able on premise with their own network loadbalancer), but on premise is probably better. If we want to be accurate, we can say "on premise without a load balancer", or "on premise clusters normally do not come with a network loadbalancer" or something along that line.

2022-04-05 10:00 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Over the last year, kubevirt has integrated with MetalLB in order to support fault-tolerant access to an application
Done

2022-04-05 10:04 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +through an external IP address. As a Cluster administrator using a bare-metal cluster, now it's possible to add MetalLB
according to metalLB [page](https://metallb.universe.tf/):
```
MetalLB is a load-balancer implementation for bare metal [Kubernetes](https://kubernetes.io/) clusters, using standard routing protocols.
```
So I think we're not miss-advertising here. no?

2022-04-05 10:06 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +implementation in clusters that don’t run on a cloud provider, such as bare-metals.
Let's wait to see what @fedepaol says on your previous [comment](https://github.com/kubevirt/kubevirt.github.io/pull/837#discussion_r841604077)

2022-04-05 10:07 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +the local network. This method announces the IPs in ARP (for IPV4) and NDP (for IPV6) protocols over the network. From a
Done

2022-04-05 10:07 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +- BGP mode
yep I'll change it.. thanks!

2022-04-05 10:08 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To read more on MetalLB concepts, implementation and limitations, please read [here](https://metallb.universe.tf/concepts/).
Done

2022-04-05 10:09 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +With the following recipe we will end up with a nginx server running on a virtualMachine, accessible outside the cluster
fixed throughout the page

2022-04-05 10:10 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +using MetalLB loadBalancer.
done.

2022-04-05 10:10 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To start it up follow this [guide](https://kind.sigs.k8s.io/docs/user/quick-start)
Done

2022-04-05 10:11 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +We are going to use [kind](https://kind.sigs.k8s.io) provider as an ephemeral Kubernetes cluster.
fixed.

2022-04-05 11:16 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Now it's time to start-up a virtualMachine running nginx, using this yaml:
removed.

2022-04-05 11:17 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +### Expose the virtualMachine with a typed LoaBalancer service
already changed to virtual machine

2022-04-05 11:54 UTC, RamLavi commented
/hold cancel

2022-04-05 14:09 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +This mode provides a real load-balancing behavior, By establishing BGP peering sessions with the network routers. They in turn advertise the external IPs of the `LoadBalancer` service, distributing t
```suggestion
This mode provides real load-balancing behavior, by establishing BGP peering sessions with the network routers - which advertise the external IPs of the `LoadBalancer` service, distributing the load over the nodes.
```

2022-04-05 14:15 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You can confirm the operator is installed by entering the following command:
I think it would be preferable to block until it is in the correct phase, something like:

```golang
kubectl wait -nmy-metallb-operator csv metallb-operator.v0.12.0 \
  --for=jsonpath='{.status.phase}'=Succeeded --timeout=2m
```

2022-04-05 14:17 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +> - If you're running a bare-metal cluster in a colocation factory, you need to first reserve this IP Address pool from your hosting provider. Alternatively, if you're running on a purely private clu
What is a colocation factory ? I would expect an explanation along the term whenever it is introduced.

I would also drop the word `purely`. It adds nothing imo.

2022-04-05 14:20 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +              sudo systemctl start nginx
I would prefer to see a cloud config instead of a bash script snippet:
```suggestion
              #cloud-config
              password: fedora
              chpasswd: { expire: False }
              packages:
                - nginx
              runcmd:
                - [ "systemctl", "enable", "--now", "nginx" ]
```

2022-04-05 14:23 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  sessionAffinity: None
nit: This is the default; it can be omitted.

2022-04-05 14:48 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +This mode does not implement Load-balancing behavior provides a failover mechanism where one node owns the `LoadBalancer` service, until the node fails and another node is chosen. In a strict sense,
```suggestion
This mode - which does not implement Load-balancing behavior - provides a failover mechanism where a single node owns the `LoadBalancer` service, until it fails, triggering another node to be chosen as service owner. This configuration mode makes the IPs reachable from the local network. 

This method announces the IPs using ARP (for Ipv4) or NDP (for Ipv6) protocols over the network. From a network perspective, the node appears to have multiple IP addresses assigned to a network interface on the chosen node.
```

I am a bit confused about the second paragraph though ... I unfortunately cannot provide any assistance in re-writing it.

2022-04-06 05:58 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +through an external IP address. As a Cluster administrator using a bare-metal cluster, now it's possible to add MetalLB
I actually did not see @fedepaol 's comment when I posted mine on top of it. I'll change it accordingly of course :)

2022-04-06 06:03 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +implementation in clusters that don’t run on a cloud provider, such as bare-metals.
fixed.

2022-04-06 06:17 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +MetalLB is responsible for assigning/unassigning an external IP Address to your service, using IPs from pre-configured pools. In order for the external IPs to be announced externally, MetalLB works i
done

2022-04-06 06:20 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +This mode provides a real load-balancing behavior, By establishing BGP peering sessions with the network routers. They in turn advertise the external IPs of the `LoadBalancer` service, distributing t
done

2022-04-06 06:34 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +> - If you're running a bare-metal cluster in a colocation factory, you need to first reserve this IP Address pool from your hosting provider. Alternatively, if you're running on a purely private clu
it's basically the opposite of a private cluster you spin up on a machine. it means you share the network with others (clusters, hosts, etc..), and so you need to approach your (factory) network admin to give you a lease of IPs for metalLB to use.

2022-04-06 06:45 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You can confirm the operator is installed by entering the following command:
I actually think both options are not so great.
The reason is that after installing the MetalLB operator, it takes a few moments for the csv to appear, so you'll get 
```
$ kubectl wait -nmy-metallb-operator csv metallb-operator.v0.12.0   --for=jsonpath='{.status.phase}'=Succeeded --timeout=2m
Error from server (NotFound): clusterserviceversions.operators.coreos.com "metallb-operator.v0.12.0" not found
```
Moreover, your suggestion will break as soon as they do a new operator release.

To sum it, the confirmation command `kubectl get csv -n my-metallb-operator` actually comes from the MetalLB installation guide, so I figured they know best..

2022-04-06 07:00 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +> - If you're running a bare-metal cluster in a colocation factory, you need to first reserve this IP Address pool from your hosting provider. Alternatively, if you're running on a purely private clu
I changed the notes a little, tell me if it's more understandable now

2022-04-06 07:03 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  sessionAffinity: None
only `sessionAffinity`?

2022-04-06 07:07 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +              sudo systemctl start nginx
Like! done

2022-04-06 07:12 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +This mode does not implement Load-balancing behavior provides a failover mechanism where one node owns the `LoadBalancer` service, until the node fails and another node is chosen. In a strict sense,
rephrased, tell me what you think.

2022-04-06 07:21 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +that you will need `cluster-admin` privileges.
done

2022-04-06 08:11 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  sessionAffinity: None
`allocateLoadBalancerNodePorts` also defaults to true: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#service-v1-core

If I were you, I'd check all of them are not the defaults.

2022-04-06 10:38 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  sessionAffinity: None
ack, thanks!

2022-04-06 16:40 UTC, maiqueb requested changes

2022-04-06 16:40 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +As a Cluster administrator using an on-prem cluster without a network load balancer, now it's possible to add MetalLB operator and gain a load-balancer capabilities (with Services of type LoadBalance
```suggestion
As a Cluster administrator using an on-prem cluster without a network load balancer, now it's possible to use MetalLB operator to provide load-balancer capabilities (with Services of type LoadBalancer) to virtual machines.
```

2022-04-06 16:40 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  How you get IP address pools for MetalLB depends on your environment:
I find this sentence strangely positioned. Are you sure you want this to read:

`IP Address allocation: How you get IP address pools for MetalLB depends on your environment:` ?

2022-04-06 16:40 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You can confirm the operator is installed by entering the following command:
> Moreover, your suggestion will break as soon as they do a new operator release.

Using a variable would address that - and still, having the version of something as part of its name is .... not a smart move. 

> I think we should keep it, as the confirmation command kubectl get csv -n my-metallb-operator I mentioned actually comes from the MetalLB installation guide, so I figure they know best..

I'm just trying to make the reader's life easier: use a blocking command that unblocks when state == desiredState is more comfortable than repeating a command until the reader sees what's expected, but feel free to discard this opinion; I won't insist.

2022-04-07 08:14 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You can confirm the operator is installed by entering the following command:
> > Moreover, your suggestion will break as soon as they do a new operator release.
> 
> Using a variable would address that - and still, having the version of something as part of its name is .... not a smart move.
> 
> > I think we should keep it, as the confirmation command kubectl get csv -n my-metallb-operator I mentioned actually comes from the MetalLB installation guide, so I figure they know best..
> 
> I'm just trying to make the reader's life easier: use a blocking command that unblocks when state == desiredState is more comfortable than repeating a command until the reader sees what's expected, but feel free to discard this opinion; I won't insist.


using the version is indeed... a choice... but it's not in our hands..
I do agree that `wait` is cooler, but still prefer the "get csv" option in this particular case. I will add a line that it may take a few seconds for the CSV to appear. Hope you find it ok by you.

2022-04-07 08:16 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +As a Cluster administrator using an on-prem cluster without a network load balancer, now it's possible to add MetalLB operator and gain a load-balancer capabilities (with Services of type LoadBalance
Done

2022-04-07 08:18 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You can confirm the operator is installed by entering the following command:
It's fine.

2022-04-07 08:18 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  How you get IP address pools for MetalLB depends on your environment:
rephrased. what do you think?

2022-04-07 08:24 UTC, maiqueb approved these changes
Short. concise, and useful.

Thank you.

2022-04-07 08:25 UTC, phoracek commented
/test kubevirt-io-presubmit-link-checker

2022-04-07 09:14 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Over the last year, Kubevirt has integrated with MetalLB in order to support fault-tolerant access to an application through an external IP address.
true :) rephrased.

2022-04-07 09:15 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +As a Cluster administrator using an on-prem cluster without a network load balancer, now it's possible to add MetalLB operator and gain a load-balancer capabilities (with Services of type LoadBalance
Done

2022-04-07 09:16 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +- Layer 2 mode (ARP/NDP)
Fixed.

2022-04-07 09:17 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +## Demo: virtual machine with external IP and MetalLB load balancer
Done

2022-04-07 09:20 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +As a Cluster administrator using an on-prem cluster without a network load balancer, now it's possible to add MetalLB operator and gain a load-balancer capabilities (with Services of type LoadBalance
aligned to `load-balancer`

2022-04-07 09:21 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To start it up follow this [guide](https://kind.sigs.k8s.io/docs/user/quick-start/#installation).
Done

2022-04-11 12:05 UTC, phoracek requested changes

2022-04-11 12:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +> Note: Since this demo is using a kind cluster, we want this range to be on the docker kind network. For more information, see [link](https://kind.sigs.k8s.io/docs/user/loadbalancer/)
This guide describes how to install MetalLB. It is confusing to list this under a section that waits for MetalLB to get installed

2022-05-01 10:47 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  - Alternatively, if you're running on a private cluster, you can use one of the private IP Address spaces (a.k.a RFC1918 addresses). Such addresses are free, and work fine as long as you’re only pr
You're right, these pre-requirements certainly do not fit here. Removed
Regarding the note - I will add only the necessary things needed for this demo.

2022-05-01 10:48 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +> Note: Since this demo is using a kind cluster, we want this range to be on the docker kind network. For more information, see [link](https://kind.sigs.k8s.io/docs/user/loadbalancer/)
I agree, this deserves a proper section.

2022-05-02 09:05 UTC, phoracek requested changes

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To start it up follow this [installation guide](https://kind.sigs.k8s.io/docs/user/quick-start/#installation).
This should be in the prerequirements section.

Also, could we change this to "First install kind on your machine following its installation guide". The installation is platform specific and may change, so it makes sense to refer an external source.

However, I would ask to list everything happening after installation here, starting with the commands starting a kind cluster.

If we split it like that, it would be clear "install kind however you want, then come back and we will prepare the environment"

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +On macOS and Windows however, docker does not expose the docker network to the host, rendering the external IP unreachable from other kind nodes. In order to workaround this, one could expose pods an
Once the kind installation is moved to this section, could we move this paragraph to a another  subsection "External IPs on macOS and Windows"?

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +
```suggestion
### Deploying cluster

... How to start kind
```

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the ip range from. The output should contain a cidr such as 172.18.1.0/16
Could you explain how this pool relates to my docker installation, and is this different on macOS, windows?

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +In order to complete the Layer 2 mode configuration, we need to set a range of IP Addresses for the LoadBalancer to use. We want this range to be on the docker kind network, so by using this command:
```suggestion
In order to complete the Layer 2 mode configuration, we need to set a range of IP addresses for the LoadBalancer to use. We want this range to be on the docker kind network, so by using this command:
```

2022-05-02 09:05 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the ip range from. The output should contain a cidr such as 172.18.1.0/16
```suggestion
You should get the subclass you can set the IP range from. The output should contain a cidr such as 172.18.1.0/16
```

2022-05-03 08:03 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +To start it up follow this [installation guide](https://kind.sigs.k8s.io/docs/user/quick-start/#installation).
I agree. Done.

2022-05-03 08:10 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +On macOS and Windows however, docker does not expose the docker network to the host, rendering the external IP unreachable from other kind nodes. In order to workaround this, one could expose pods an
yes, but I think it this subsection should remain under `Prerequirement` section.
Done.

2022-05-03 08:12 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +
Done

2022-05-03 08:29 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the ip range from. The output should contain a cidr such as 172.18.1.0/16
The pool uses the IP space provided by kind on docker, this is only relevant for Linux. 
macOS, windows will need to set their own network, as mentioned on `External IPs on macOS and Windows` section.
I will rephrase to make that clearer, tell me what you think.

2022-05-03 08:30 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +In order to complete the Layer 2 mode configuration, we need to set a range of IP Addresses for the LoadBalancer to use. We want this range to be on the docker kind network, so by using this command:
Done

2022-05-03 08:30 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the ip range from. The output should contain a cidr such as 172.18.1.0/16
Done

2022-05-03 11:53 UTC, phoracek reviewed
Worked for me, some minor comments. I'm yet to re-review the text

2022-05-03 11:53 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Then to start using the cluster:
How is the following command using the cluster?

2022-05-03 11:53 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
```suggestion
There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-operator) and click the Install button. 
```

2022-05-03 11:53 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
The OLM 0.21.1 installation command fails for me on a fresh kind cluster with

```
The CustomResourceDefinition "clusterserviceversions.operators.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

2022-05-03 11:53 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Finally, we can check that the nginx server is accessible from outside the cluster:
Could you add a note explaining that it may take a while before the VM becomes available? Or better, show how to wait for it to become available

2022-05-03 11:53 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +pub-date: April 03
Let's update this, in case we forget to update it later before publishing

2022-05-03 13:02 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Then to start using the cluster:
mmm.. let me rephrase it

2022-05-03 13:07 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
strange.. lemme try installing again

2022-05-03 13:08 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +pub-date: April 03
Done

2022-05-03 13:17 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
Yes I see it. OLM has an open issue https://github.com/operator-framework/operator-lifecycle-manager/issues/2767 on this.
well it's not blocking or anything. Do you think we should install MetalLB a different way?

2022-05-03 13:19 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
I stand corrected, it's not really working.. I'll look for another way to install MetalLB

2022-05-03 15:34 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
It failed for me on OLM 0.21.1, but 0.20.0 worked ok

2022-05-04 04:45 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Finally, we can check that the nginx server is accessible from outside the cluster:
I added a note, though it is not related to the vm being ready. It looks like the url simply takes some time to work after setting the service. 
@fedepaol do you know why this happens? I wonder if there is something we can "wait" upon being ready and not simply wait fr the url to work..

2022-05-04 04:48 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are many ways to install MetalLB. For the sake of this example, we will install MetalLB operator on the cluster. To do this, please follow this [link](https://operatorhub.io/operator/metallb-op
Moved to installing via manifest.

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +On macOS and Windows however, docker does not expose the docker network to the host, rendering the external IP unreachable from other kind nodes. In order to workaround this, one could expose pods an
How would I then configure the address range in the MetalLB ConfigMap?

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +In order to interact with the specific cluster created:
Sorry, I still don't understand what are you suggesting here and how is calling `cluster-info` useful in the remainder of the  post

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the IP range from. The output should contain a cidr such as 172.18.0.0/16
```suggestion
You should get the subclass you can set the IP range from. The output should contain a cidr such as 172.18.0.0/16.
```

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Installing Kubevirt on the cluster
Could you move this under "Installing components"? That way we would split the post into:
1. Intro
2. Prerequisites
3. Cluster deployment
4. Components deployment
5. Network resources configuration
6. Network utilization

So it would run from the lowest layer to the highest.

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Setting Address Pool to be used by the LoadBalancer
This should not be a part of component installation

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +## Introducing MetalLB
```suggestion
## MetalLB
```
The headline above already says "Introduction", saying it again (despite this is not nested) seems redundant

2022-05-04 08:21 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +##### External IPs on macOS and Windows
This is so nested that our website does not have a CSS style defined for it. What about removing the prerequirements headline and just keeping its list under the section above. Then you can remove one level of nesting on this one

2022-05-04 08:25 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +description: This post illustrates setting up a virtual machine with MetalLb loadBalance service.
Done

2022-05-04 08:33 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +On macOS and Windows however, docker does not expose the docker network to the host, rendering the external IP unreachable from other kind nodes. In order to workaround this, one could expose pods an
in short - the same. 

This section deals not with the MetalLB ConfigMap, but with IP choosing considerations. 
It's basically saying, if you're not using docker on linux, then you need to configure yourself the ip range is reachable from your pc console.
But once you made sure that IP is reachable, the configuring MetalLB ConfigMap is the same..

2022-05-04 08:36 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +In order to interact with the specific cluster created:
when creating kind cluster, you may have more than 1 clusters to use:
```
$ kind get clusters
kind
kind-2
```

with `kubectl cluster-info --context kind-kind` you choose to work with the specific cluster you want kubectl to point to..

2022-05-04 08:38 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +You should get the subclass you can set the IP range from. The output should contain a cidr such as 172.18.0.0/16
Done

2022-05-04 08:40 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Installing Kubevirt on the cluster
not sure I understand you. `#### Installing Kubevirt on the cluster` **is** under `### Installing components`, isn't it?

2022-05-04 08:41 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Setting Address Pool to be used by the LoadBalancer
I agree, moved to be under `#### Installing MetalLB on the cluster`

2022-05-04 08:41 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +## Introducing MetalLB
Done

2022-05-04 08:43 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +##### External IPs on macOS and Windows
I like!

2022-05-04 09:27 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +In order to interact with the specific cluster created:
I see, so you are calling this to make sure that in case somebody changed the kind context before running this demo, we change it back to the implicit default name "kind-kind". Should set a specific context name while calling `kind create cluster` to make the connection clear?

2022-05-11 08:48 UTC, phoracek reviewed
Just some typos. I'm ok with this PR once these are resolved

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are [many ways](https://metallb.universe.tf/installation/) to install MetalLB. For the sake of this example, we will install MetalLB via Manifests. To do this, follow this [guide](https://metal
```suggestion
There are [many ways](https://metallb.universe.tf/installation/) to install MetalLB. For the sake of this example, we will install MetalLB via manifests. To do this, follow this [guide](https://metallb.universe.tf/installation/#installation-by-manifest). 
```

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +### Expose the virtual machine with a typed `LoaBalancer` service
```suggestion
### Expose the virtual machine with a typed `LoadBalancer` service 
```

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Installing Kubevirt on the cluster
Nevermind. Not sure what I meant here

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Now it's time to start-up a virtual machine running nginx using this yaml:
```suggestion
Now it's time to start-up a virtual machine running nginx using the following yaml.
```

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +`addresspool-sample1` and also add the selector `metallb-service: nginx`
```suggestion
`addresspool-sample1` and also add the selector `metallb-service: nginx`:
```

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Notice that the service got assigned with an external IP from the range assigned by the PoolAddress:
```suggestion
Notice that the service got assigned with an external IP from the range assigned by the address pool: 
```

?

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Example output
```suggestion
Example output:
```

2022-05-11 08:48 UTC, phoracek commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Example output
```suggestion
Example output:
```

2022-05-11 12:11 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +description: This post illustrates setting up a virtual machine with MetalLB loadBalance service.
Done

2022-05-11 12:11 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +MetalLB is responsible for assigning/unassigning an external IP Address to your service, using IPs from pre-configured pools. In order for the external IPs to be announced externally, MetalLB works i
Done

2022-05-11 12:12 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +  This mode - which actually does not implement real Load-balancing behavior - provides a failover mechanism where a single node owns the `LoadBalancer` service, until it fails, triggering another no
Done

2022-05-11 12:12 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +There are [many ways](https://metallb.universe.tf/installation/) to install MetalLB. For the sake of this example, we will install MetalLB via Manifests. To do this, follow this [guide](https://metal
Done

2022-05-11 12:12 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +### Expose the virtual machine with a typed `LoaBalancer` service
Good catch! Done

2022-05-11 12:13 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Now it's time to start-up a virtual machine running nginx using this yaml:
Done

2022-05-11 12:13 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +`addresspool-sample1` and also add the selector `metallb-service: nginx`
Done

2022-05-11 12:14 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Notice that the service got assigned with an external IP from the range assigned by the PoolAddress:
Right, now that we are not using the MetalLB operator, `PoolAddress` has no meaning

2022-05-11 12:15 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +Example output
Done

2022-05-11 12:19 UTC, RamLavi commented
@phoracek [ready](https://github.com/kubevirt/kubevirt.github.io/compare/762f41674a562ff67f02d166ece7b4edaa7a080a..9c84efd031765944da4a6a6a85a60fbcdf07ec25) for your re-review

2022-05-12 11:45 UTC, phoracek commented
/lgtm

@maiqueb could you please take a final look?

2022-05-23 08:59 UTC, maiqueb reviewed
/lgtm
/hold

Holding in case you want to re-work the sections. You can remove the hold if you prefer @RamLavi .

2022-05-23 08:59 UTC, maiqueb commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Installing Kubevirt on the cluster
I think I do:

- Cluster deployment: this one is creating the kind cluster
- Components deployment: this one is installing metalLB and KubeVirt in the cluster
- Network resources configuration: this one is configuring the metalLB pool
- Network utilization: this one is creating the VM and service

Does it make sense ? I share the concern @phoracek 's mentioned in https://github.com/kubevirt/kubevirt.github.io/pull/837/files#r864557203 ... That is part of the cluster configuration, and probably deserves to live in a separate section.

2022-05-23 09:50 UTC, RamLavi commented on _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> +#### Installing Kubevirt on the cluster
I like it. Done.
Let me know what you think

2022-05-23 10:03 UTC, maiqueb commented
/lgtm
/hold cancel

Thanks.

2022-05-23 10:50 UTC, phoracek reviewed
/approve

2022-05-23 10:51 UTC, merged