blog: post about secondary ovn-k localnet networks
kubevirt/kubevirt.github.io pull request #907
Opened 2023-05-30 16:13 UTC by maiqueb

This type of networks allows connectivity to the physical network underlay.

**What this PR does / why we need it**:
This PR shows how to create OVN-K secondary networks to interconnect VMs
on an SDN network with access to the physical network underlay.

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

2023-05-30 16:13 UTC, maiqueb commented
/cc @phoracek

2023-06-13 12:29 UTC, phoracek requested changes

2023-06-13 14:28 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +### Configuring the underlay
Is it better now ?

2023-06-22 22:22 UTC, cwilkers commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +```yaml
This renders oddly as yaml, it should probably be text or bash like the one above.

2023-06-22 22:27 UTC, cwilkers requested changes
It looks good, but could use a little consistency and formatting in the shell examples, as pointed out.

2023-06-22 22:27 UTC, cwilkers commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +```bash
You have a mix of prompt styles. It would be best to have some sort of prompt, even just a `$` to separate commands from their output.

2023-06-23 07:34 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +```bash
Good point. Is it better now ? 

I've only added in to places where I had mixed prompts.

2023-06-23 07:34 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +```yaml
Oh good catch. Thank you!

2023-06-23 13:51 UTC, cwilkers commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +```bash
Much better, yes

2023-06-23 13:53 UTC, cwilkers commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +These two VMs can be used for the OVS bridge sharing scenario (two physical
I'm counting four VMs, did you mean to say two sets of two?

2023-06-23 14:03 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +These two VMs can be used for the OVS bridge sharing scenario (two physical
Right. Is it better now ?

2023-06-26 11:12 UTC, phoracek requested changes
A nit. The rest looks great, thanks!

2023-06-26 11:12 UTC, phoracek commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +	kubectl -n ovn-kubernetes exec -ti $node -- ovs-vsctl set open . external_ids:ovn-bridge-mappings=physnet:breth0,localnet.network_br-localnet:ovsbr1
```suggestion
	kubectl -n ovn-kubernetes exec -ti $node -- ovs-vsctl set open . external_ids:ovn-bridge-mappings=physnet:breth0,localnet_network_br-localnet:ovsbr1
```

Typo?

2023-06-27 11:08 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +	kubectl -n ovn-kubernetes exec -ti $node -- ovs-vsctl set open . external_ids:ovn-bridge-mappings=physnet:breth0,localnet.network_br-localnet:ovsbr1
Nope. the OVN-K mappings nasty algorithm under the hood replaces dashes with periods ...

One more thing for the wrapper to do.
@phoracek

2023-06-27 11:17 UTC, phoracek commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +	kubectl -n ovn-kubernetes exec -ti $node -- ovs-vsctl set open . external_ids:ovn-bridge-mappings=physnet:breth0,localnet.network_br-localnet:ovsbr1
I see

2023-06-27 11:24 UTC, phoracek commented
/lgtm
/approve
/hold

Holding for @cwilkers to get a chance to +1 or -1 this too

2023-06-27 14:31 UTC, cwilkers commented
I did a quick skim, the examples look good to me now. Thanks!

/release-hold
/lgtm

2023-06-27 14:33 UTC, maiqueb commented
@cwilkers did you mean to `/hold cancel` ? 

(I'm unaware if `/release-hold` is supposed to work, but looks like it didn't ...)

2023-06-27 14:33 UTC, maiqueb commented
/hold cancel

going ahead with it. 

Thanks all.

2023-06-27 14:35 UTC, merged

2023-06-27 14:37 UTC, cwilkers commented
@maiqueb Oops, I looked up the commands and mis-remembered `remove-hold`. In completely random news, there is also a /honk command to add a goose to a PR. Do with that knowledge what you will.