WIP Add instancetype.kubevirt.io/v1beta1 update post
kubevirt/kubevirt.github.io pull request #908
Opened 2023-06-22 14:33 UTC by lyarwood

**What this PR does / why we need it**:

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

2023-06-22 17:49 UTC, lyarwood commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +# We can see that the VirtualMachineInstance is exposing `128Mi` of memory
Yes correct, `.spec.memory.guest` is the total guest visible memory and we are simply providing less actual resources to the eventual pod hosting the guest.

2023-06-22 17:49 UTC, lyarwood commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +The request is invalid: spec.instancetype: failure checking preference requirements: insufficient Memory resources of 128Mi provided by instance type, preference requires 512Mi
Yes I can make it clear that this is expected.

2023-06-22 17:49 UTC, lyarwood commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +The request is invalid: spec.template.spec.domain.cpu.cores: failure checking preference requirements: insufficient CPU resources of 0 vCPU provided by VirtualMachine, preference requires 2 vCPU prov
As above, I'll make it clear this is expected.

2023-06-22 17:50 UTC, lyarwood commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +Additionally the following optional bool labels have also been added to
Will do.

2023-06-22 17:50 UTC, lyarwood commented
> I have just a few comments, mostly for possible clarification. All can probably be safely ignored.
> 
> I like the blog post, very informative and written for easy understanding.

Thanks, I'll clean this up tomorrow. FWIW this is based on the following personal blog post, I've dropped the bugfix section as I'm not sure how useful that would be in this particular blog:

https://blog.yarwood.me.uk/2023/06/22/kubevirt_instancetype_update_5/

2023-06-23 12:43 UTC, lyarwood commented
/unhold

2023-08-02 16:57 UTC, lyarwood commented
@jobbler @cwilkers I forgot to follow up with this after the `v1.0.0` release, do you think this can be published now?

2023-09-11 08:32 UTC, lyarwood commented
/close

2023-09-18 08:38 UTC, lyarwood commented
/reopen

2023-09-21 19:53 UTC, cwilkers requested changes
Looks good, I just identified some formatting issues in the preview that could affect readability

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/8235
Can you put this into a markdown anchor? It's not clickable in the preview.
```suggestion
[https://github.com/kubevirt/kubevirt/issues/8235](https://github.com/kubevirt/kubevirt/issues/8235)
```

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +Amongst other things new version introduces a single new instance type attribute:
```suggestion
Amongst other things the new version introduces a single new instance type attribute:
```

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +The request is invalid: spec.instancetype: failure checking preference requirements: insufficient Memory resources of 128Mi provided by instance type, preference requires 512Mi
You're missing the EOF marker here to separate the command from its output.

Also, the output scrolls horizontally since it is in the code block, and since the code block is several screens long, the scroll bar is not reachable (at least in my browser). Can you break this up, perhaps even breaking the output into a separate code block to avoid this issue?

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +### `instancetype.kubevirt.io/v1alpha{1,2} deprecation`
This doesn't quite render like a header because of the inline code block. Can you try:
```suggestion
### Deprecation of `instancetype.kubevirt.io/v1alpha{1,2}`
```

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/9909
Another bare link, not clickable

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/pull/9753
Same here

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +### `virtctl image-upload`
Another weirdly rendered header, consider not using code blocks in headers

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +# Use virtctl to create a VirtualMachine manifest using the inferFromVolume option for the instance type and preference
Consider breaking up this line to be no longer than the longest actual code line, it is causing a scrollbar.

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/common-instancetypes/releases/tag/v0.3.0
bare url

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Finstancetype
bare url

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/9898
bare url

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/9899
bare url

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/9909
bare url

2023-09-21 19:53 UTC, cwilkers commented on _posts/2023-06-22-KubeVirt-Instancetypes-v1beta1.md
> +https://github.com/kubevirt/kubevirt/issues/8591
bare url

2024-02-18 21:28 UTC, closed without merging