Add post about OVN-Kubernetes multi-net policies
kubevirt/kubevirt.github.io pull request #911
Opened 2023-07-10 13:13 UTC by maiqueb

**What this PR does / why we need it**:

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

2023-07-10 14:26 UTC, maiqueb commented
/cc @phoracek

2023-07-16 20:25 UTC, orelmisan reviewed
Thank you @maiqueb for the interesting blog post.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +OVN-Kubernetes implements this API, and configures access control accordingly
```suggestion
[OVN-Kubernetes](https://github.com/ovn-org/ovn-kubernetes) implements this API, and configures access control accordingly
```

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +selectors prevent the live-migration of Virtual Machines.
Could you please refer the reader to a source or give a note about why the usage of the above selectors prevents live migrations?

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +The [following section](#environment-setup) will show you how to create a
I think the `#environment-setup` link is broken.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +This will get you a running kind cluster, configured to use OVN-Kubernetes as
How many nodes will this cluster have?

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +[multus-cni](https://github.com/k8snetworkplumbingwg/multus-cni) in the cluster.
nit: There is already a link to multus above.
Please consider removing it.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +to install the latest released version (currently, v0.59.2).
```suggestion
to install the latest released version (currently, v1.0.0).
```

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +## Demo
Could you please give a high-level description of what the setup will look like?
A block diagram could be nice.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +  config: |2
nit: Is this 2 intentional?
If so, what does it mean?

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +Let's now provision our VMs.
Please consider moving the table bellow to here, so the reader will understand what are the differences between all of the following VMs, without going over their spec.

Its also worth mentioning IMO that all of the entities (NAD and VMs) are at the `default` namespace.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +            memory: 1024Mi
nit: According to @enp0s3, its better to use the `guest` field of http://kubevirt.io/api-reference/v1.0.0/definitions.html#_v1_memory to require memory for the guest.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +- vm6: 10.200.0.6
Please consider moving this part before the VM specs.

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +
Please consider adding a sentence regarding the fact that you are about to connect to the VMs' serial console using the virtctl utility (with a link to its documentation).

2023-07-16 20:25 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +![MultiNetworkPolicy is provisioned](/assets/2023-07-10-OVN-kubernetes-secondary-networks-policies/02-no-access.png)
Please consider moving this explanation before the `MultiNetworkPolicy`, so it will be easier to understand what will happen before applying the manifest.

2023-07-17 08:52 UTC, maiqueb reviewed
Thank you for the thorough review @orelmisan

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +This will get you a running kind cluster, configured to use OVN-Kubernetes as
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +[multus-cni](https://github.com/k8snetworkplumbingwg/multus-cni) in the cluster.
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +Let's now provision our VMs.
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +            memory: 1024Mi
ignoring this nit since it's not relevant.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +- vm6: 10.200.0.6
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +![MultiNetworkPolicy is provisioned](/assets/2023-07-10-OVN-kubernetes-secondary-networks-policies/02-no-access.png)
Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +## Demo
I'm stating below this cluster is composed of one control plane node plus two worker nodes.

What more info are you expecting to have ?

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +The [following section](#environment-setup) will show you how to create a
Good catch.

Done.

2023-07-17 08:52 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +selectors prevent the live-migration of Virtual Machines.
Is the provided explanation good enough, or do you think it should be more detailed ?

2023-07-17 10:31 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +selectors prevent the live-migration of Virtual Machines.
Thank you for adding the explanation.
I think its enough.

2023-07-17 10:34 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +## Demo
You can resolve this thread.
The information you've added below is enough.

2023-07-17 10:35 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +  config: |2
Thank you for the explenation.

2023-07-17 10:41 UTC, orelmisan approved these changes
Thank you for the changes @maiqueb.

2023-07-17 10:41 UTC, orelmisan commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +- vm6: 10.200.0.6.
nit:
```suggestion
- vm6: 10.200.0.6
```

2023-07-17 11:10 UTC, orelmisan approved these changes

2023-07-21 08:04 UTC, phoracek requested changes
I like it. Clean yet comprehensive

2023-07-21 08:04 UTC, phoracek commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +from the network policy pod selector `matchLabels` stanza).
This is correct, but confusing since we never defined any Pods, just VMs.

Would you please use this to explain that this applies to both Pods and VMs. Where the `podSelector.matchLabels` matches labels set in VM's `spec.template.metadata.labels`?

Our users should not need to know that a VM is turned into a VMI which is then turned into a Pod.

2023-07-21 08:04 UTC, phoracek commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +**only if** the traffic originates from within the `10.200.0.0/30` CIDR range.
```suggestion
**only if** the traffic originates from within the `10.200.0.0/30` CIDR range
(IPs 10.200.0.1-3).
```

For the less network savvy.

2023-07-21 08:45 UTC, maiqueb reviewed
Thanks for reviewing.

2023-07-21 08:45 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +pub-date: July 10
Done.

2023-07-21 08:45 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +## Demo
OK, thanks.

2023-07-21 08:45 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +require OVN-K managed IPAM, and currently the live-migration feature is only
Your traffic will be dropped since the "allow" list IPs will be empty - OVN doesn't know what addresses are assigned to the logical ports.

2023-07-21 08:45 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +and upstream latest multus-cni deployed.
Done.

2023-07-21 08:45 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +from the network policy pod selector `matchLabels` stanza).
I agree with your conclusion, but I don't understand the rest. 

Is it better if I say `We will now provision a MultiNetworkPolicy applying to all VMs attached to` instead (while leaving the rest unchanged) ?

2023-07-21 14:36 UTC, phoracek commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +from the network policy pod selector `matchLabels` stanza).
```suggestion
We will now provision a `MultiNetworkPolicy` applying to all the VMs defined above.
To do this mapping correctly, the policy has to:

* Be in the same namespace as the VM.
* Set `k8s.v1.cni.cncf.io/policy-for` annotation matching the secondary network used by the VM.
* Set `matchLabels` selector matching the labels set on VM's `spec.template.metadata`.
```

2023-07-24 10:10 UTC, maiqueb commented on _posts/2023-07-10-OVN-kubernetes-secondary-networks-policies.md
> +from the network policy pod selector `matchLabels` stanza).
Done.

2023-07-24 10:23 UTC, maiqueb commented
Trying to get the date right ... seems the order on the "recent" blogs is being read not from the post date, but from the commit date ... (at least that's what I think, not sure yet).

@phoracek other than that, it should be good to go.

2023-07-24 10:52 UTC, phoracek commented
/lgtm
/approve

Thanks for posting this!

2023-07-24 10:55 UTC, merged