WIP Localnet: various small fixes
kubevirt/kubevirt.github.io pull request #913
Opened 2023-07-23 09:26 UTC by oshoval

**What this PR does / why we need it**:

**Does this PR fix any issue?** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

> Fixes #

**Special notes for your reviewer**:

2023-07-23 11:00 UTC, oshoval commented
/cc @maiqueb

2023-08-23 10:02 UTC, maiqueb requested changes
Some suggestions.

Do you mind fixing also the podman command ? 

Right now, it is not being properly rendered - the format is missing.

Check the attached image.

![image](https://github.com/kubevirt/kubevirt.github.io/assets/39051226/79cb409e-58a4-4b58-a7b1-c7aba8689913)

2023-08-23 10:11 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +<code>
we can't use ``` 
this what caused podman problem
https://github.com/kubevirt/kubevirt.github.io/pull/912#issuecomment-1646763162

2023-08-23 12:21 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +<code>
done
https://deploy-preview-913--kubevirtio.netlify.app/2023/ovn-kubernetes-secondary-networks-localnet

2023-08-23 12:21 UTC, oshoval commented
Addressed comments

2023-08-23 12:24 UTC, maiqueb requested changes

2023-08-23 12:24 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +podman network inspect underlay --format '{ { .NetworkInterface }}'
unfortunately this does not work:

```
$ podman network inspect kind --format '{ { .NetworkInterface }}'
{ { .NetworkInterface }}

$ podman network inspect kind --format '{{ .NetworkInterface }}'0 
podman10
```

2023-08-23 12:27 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +podman network inspect underlay --format '{ { .NetworkInterface }}'
of course it wont work, the user need to remove the space
it is just for displaying
else we need code

2023-08-23 12:45 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +podman network inspect underlay --format '{ { .NetworkInterface }}'
the whole point of this is for the user to copy paste stuff from the post into <whatever>.

Use the html tags if you need.

2023-08-23 13:28 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +podman network inspect underlay --format '{ .NetworkInterface }}'
need to fix here as well

2023-08-23 13:31 UTC, maiqueb approved these changes
Minor nits. 

If you have more comments from the maintainers, please take these suggestions into account.

2023-08-23 13:31 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +The command output will be the bridge name, for example `podman3`.
```suggestion
The command will output the bridge name - e.g. `podman3`.
```

2023-08-23 13:31 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +We can use it in the following command
I'd prefer if we indicated what we're trying to achieve.

```suggestion
Then, we configure the bridge implementing the secondary network with the gateway IP address.
```

2023-08-23 13:51 UTC, cwilkers commented
Hi!
If you still want all your code blocks to look the same (they really render differently between the code blocks and triple-backticks) I figured out an escape for the `{{` literal:

```text
podman network inspect underlay --format '{{ "{{" }} .NetworkInterface }}'
```

2023-08-23 13:52 UTC, maiqueb commented
> Hi! If you still want all your code blocks to look the same (they really render differently between the code blocks and triple-backticks) I figured out an escape for the `{{` literal:
> 
> ```
> podman network inspect underlay --format '{{ "{{" }} .NetworkInterface }}'
> ```

@oshoval please try this out !!! Thanks @cwilkers !

2023-08-23 14:19 UTC, oshoval commented
> Hi! If you still want all your code blocks to look the same (they really render differently between the code blocks and triple-backticks) I figured out an escape for the `{{` literal:
> 
> ```
> podman network inspect underlay --format '{{ "{{" }} .NetworkInterface }}'
> ```

Thanks, trying to see how it looks like on netlify

2023-08-23 14:28 UTC, oshoval commented
Due to the latest changed the comments are outdated
pushed the changes, ptal

2023-08-23 14:30 UTC, maiqueb commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +**NOTE:** Docker has a little different format; we will need to use the following command instead:
Sorry, I didn't notice before how weird this read. My bad.

```suggestion
**NOTE:** for docker, please use the following command:
```

2023-08-23 14:37 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +**NOTE:** Docker has a little different format; we will need to use the following command instead:
done

2023-08-24 10:46 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +The command output will be the bridge name, for example `podman3`.
outdated, since removed the new text

2023-08-24 10:46 UTC, oshoval commented on _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
> +We can use it in the following command
outdated, since removed the new text

2023-08-24 11:42 UTC, oshoval commented
Addressed comments

2023-08-29 12:04 UTC, oshoval commented
@maiqueb can you please take another look ?

2023-09-13 08:13 UTC, phoracek commented
/approve

2023-09-13 08:17 UTC, merged