[WIP] Update CDI lab to work with latest versions
kubevirt/kubevirt.github.io pull request #914
Opened 2023-08-01 08:51 UTC by alromeros

**What this PR does / why we need it**:

The CDI lab in kubevirt.io contains out-of-date processes and information, to the point where it recommends the creation of a PVC with import annotations instead of a DataVolume. The given example simply doesn't work with the latest CDI version.

Though we plan to eventually change the way CDI works with DataVolumes (check https://github.com/kubevirt/containerized-data-importer/pull/2752 for more information), the lab should at least provide a working example so users can test CDI's latest versions.

With the adoption of populators this process will require an update again soon, but since users have been reporting issues with the current lab (https://github.com/kubevirt/containerized-data-importer/issues/2830 or https://github.com/kubevirt/containerized-data-importer/issues/2645#issuecomment-1489913173) at least we should fix it for the moment.

2023-08-10 12:59 UTC, aglitke approved these changes

2023-08-10 12:59 UTC, aglitke commented on _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
> +    accessModes:
Should we leave out the volume mode and access mode?  I get that the lab is more likely to work if we choose RWO/Filesystem but is that teaching a bad behavior (since we would want RWX if possible).

2023-08-10 13:19 UTC, alromeros commented on _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
> +    accessModes:
Sure I can leave them out if preferred.

2023-08-28 14:01 UTC, cwilkers requested changes
Thanks for this important update, I just added comments asking to bring the Fedora cloud image up to latest (I think 37 currently, with 38 in beta, but I could be outdated too)

It would also be good to update the Killercoda lab (kubevirt/katacoda-scenarios)

2023-08-29 14:15 UTC, alromeros commented on _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
> +      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.raw.xz"
Good point. Thanks!

2023-08-29 23:15 UTC, cwilkers commented
/lgtm
/approve

2023-08-29 23:17 UTC, merged