Add blog on KubeVirt and Cluster Autoscaler
kubevirt/kubevirt.github.io pull request #918
Opened 2023-09-07 03:43 UTC by relaxdiego

**What this PR does / why we need it**:

This cross-posts a blog post on using KubeVirt with Cluster Autoscaler. The original can be found at: https://relaxdiego.com/2023/08/kubevirt-cas-baremetal.html

2023-09-14 16:34 UTC, aburdenthehand requested changes
Nice work! And thanks for bringing this across.
I have a couple of suggestions but also there's some syntax changes required for some of the code blocks to play nicely with our build system. You can run a [local build](https://github.com/kubevirt/kubevirt.github.io/tree/main#test-work) to test that everything renders properly.

2023-09-14 16:34 UTC, aburdenthehand commented on _posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
> +{% endhighlight %}
This syntax isn't being built properly, but if you change them to ` ``` bash` (open) and ` ``` ` (close) tags it should render properly. Same applies throughout the document.

You can see the [content guidelines here](https://github.com/kubevirt/kubevirt.github.io/blob/main/GUIDELINES.md#content) in case it's useful.

2023-09-14 16:34 UTC, aburdenthehand commented on _posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
> +zones that was declared in `cluster.yaml` so that the Cluster Autoscaler will
```suggestion
Based on the above, we will create a node group for each of the availability
zones (AZs) that was declared in `cluster.yaml` so that the Cluster Autoscaler will
```

2023-09-14 16:34 UTC, aburdenthehand commented on _posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
> +> can be scheduled in the infra nodes instead of the bare metals nodes which we
```suggestion
> can be scheduled in the infra nodes instead of the bare metal nodes which we
```

2023-09-21 09:16 UTC, relaxdiego commented
Thanks for the review @aburdenthehand! Will get those changes in soon.

2023-09-28 14:41 UTC, aburdenthehand commented
Looks good @relaxdiego - the only thing is we need you to sign your previous commit. 
I believe ```git commit --amend --signoff --no-edit``` should do the trick (since it was only the previous one commit that wasn't signed)

2023-09-29 02:28 UTC, relaxdiego commented
Thanks @aburdenthehand! Added the missing sign-off.

2023-09-29 08:21 UTC, aburdenthehand commented
/lgtm
Thanks Mark!

2023-09-29 08:21 UTC, aburdenthehand approved these changes

2023-09-29 12:46 UTC, cwilkers commented
Nice work! Thanks for the post

/approve

2023-09-29 12:49 UTC, merged

2023-09-29 13:25 UTC, relaxdiego commented
Thanks for accepting this contribution!