New blog for the v1.4 release
kubevirt/kubevirt.github.io pull request #973
Opened 2024-11-04 19:53 UTC by aburdenthehand

Adding a blog for our v1.4 release to cover key changes and hype some of our awesome new features. 

To be published alongside the release on November 12
(There's also a [user-guide PR for the release notes](https://github.com/kubevirt/user-guide/pull/850/files))

2024-11-04 20:01 UTC, jean-edouard approved these changes

2024-11-05 09:04 UTC, aburdenthehand commented
/hold

2024-11-05 11:15 UTC, alicefr commented on _posts/2024-11-12-KubeVirt-v1-4.md
> +If you've ever wanted to migrate your virtual machine PVC from one storage type to another then you'll be interested in our [volume migration])https://kubevirt.io/user-guide/storage/volume_migration/
nit: `virtual machine PVC` -> `virtual machine volume`, because this includes datavolumes as well

2024-11-05 13:38 UTC, phoracek commented on _posts/2024-11-12-KubeVirt-v1-4.md
> +The networking binding plugins have matured to Beta, and we have a new domain attachment type,[`managedTap`](https://github.com/kubevirt/kubevirt/pull/13024), and the ability to [reserve memory overh
```suggestion
The networking binding plugins have matured to Beta, and we have a new domain attachment type,[`managedTap`](https://github.com/kubevirt/kubevirt/pull/13024), and the ability to [reserve memory overhead](https://github.com/kubevirt/kubevirt/pull/12235) for binding plugins. [Network binding plugins](https://kubevirt.io/user-guide/network/network_binding_plugins/) enable vendors to provide their own VM-to-network plumbing alongside KubeVirt.
```

2024-11-05 13:39 UTC, phoracek requested changes

2024-11-05 13:39 UTC, phoracek commented on _posts/2024-11-12-KubeVirt-v1-4.md
> +We introduced [Dynamic Primary Pod NIC Names](https://github.com/kubevirt/kubevirt/pull/13018), which supports different CNIs to leverage various interface names, and added support for the `igb` netw
```suggestion
We added support for the `igb` network interface model.
```

Dynamic NIC names are not really a feature - more like a part of the binding plugins internals. I would not list it here.

2024-11-13 10:28 UTC, aburdenthehand commented on _posts/2024-11-12-KubeVirt-v1-4.md
> +We introduced [Dynamic Primary Pod NIC Names](https://github.com/kubevirt/kubevirt/pull/13018), which supports different CNIs to leverage various interface names, and added support for the `igb` netw
Done

2024-11-13 10:28 UTC, aburdenthehand commented
/unhold

2024-11-13 15:18 UTC, dhiller commented
/approve

2024-11-13 15:42 UTC, dhiller approved these changes

2024-11-13 15:42 UTC, merged